microsoft/vscode-dev-containers

containers/java-11/.devcontainer/Dockerfile, containers/java-12/.devcontainer/Dockerfile, containers/java-8/.devcontainer/Dockerfile
This PR fixes the wrong symlink to the Gradle binary and upgrades to version 5.4.1
=> [java] Fix symlink and upgrade to Gradle 5.4.1

containers/javascript-node-8/.devcontainer/Dockerfile, containers/javascript-node-lts-mongo/.devcontainer/Dockerfile, containers/javascript-node-lts/.devcontainer/Dockerfile, containers/typescript-node-8/.devcontainer/Dockerfile, containers/typescript-node-lts/.devcontainer/Dockerfile
Currently the node definitions clear out the `/opt/yarn` location in the base node images and install `yarn` using `apt-get` so it can be upgraded in-place by the user as needed. The code looks like this:
```Dockerfile
rm -rf /opt/yarn-* \
rm -f /usr/local/bin/yarn \	   
rm -f /usr/local/bin/yarnpkg \
...
```
This is wrong, because the last two paths won't be deleted.  It should be:
```Dockerfile
rm -rf /opt/yarn-* \
&& rm -f /usr/local/bin/yarn \	   
&& rm -f /usr/local/bin/yarnpkg \
...
```
However, because /opt/yarn-* is removed, the links in `/usr/local/bin` are ignored and everything works anyway.  So this is more of a cosmetic fix and **not blocking**.
=> [Non-blocking cosmetic fix] Add missing "&&" into Node definitions when updating yarn

containers/powershell/.devcontainer/Dockerfile
A lot of Microsoft containers are moving the MCR - PowerShell being one that has already made the switch.
I would recommend checking with the other containers to see if they use MCR - it's easy to check. It shows up in Docker Hub:
https://hub.docker.com/_/microsoft-powershell?tab=description
Full list:
https://hub.docker.com/publishers/microsoftowner
cc @TravisEz13
=> Use correct PowerShell container

README.md
Add missing sample projects to the documentation
* `C++`
* `Rust`
* `PHP`
=> Add missing sample projects to the documentation

containers/R/.devcontainer/Dockerfile, containers/R/.devcontainer/devcontainer.json, containers/R/.npmignore, containers/R/README.md, containers/R/test-project/sample.R
We can have `R devcontainer` added to the present vs code development container ecosystem.
=> Add R devcontainer for statistical computing

containers/java-11/.devcontainer/Dockerfile, containers/java-11/.devcontainer/maven-settings.xml, containers/java-11/README.md, containers/java-12/.devcontainer/Dockerfile, containers/java-12/.devcontainer/maven-settings.xml, containers/java-12/README.md, containers/java-8/.devcontainer/Dockerfile, containers/java-8/.devcontainer/maven-settings.xml, containers/java-8/README.md
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
Address issue #31 .
- Use openjdk as the base image.
- Comment out the steps to install maven and gradle build tools.
- Update README about how to enable maven and gradle in the Dockerfile.
=> Simplify Java Dockerfiles

containers/alpine-3.10-git/.devcontainer/Dockerfile, containers/alpine-3.10-git/.devcontainer/devcontainer.json, containers/alpine-3.10-git/.npmignore, containers/alpine-3.10-git/README.md
Now that we have Alpine support in Remote - Containers for VS Code Insiders (🎉🎉🎉), it seems to make sense to create a container definition similar to the Debian / Ubuntu.
One of the things I noticed was the C++ extension didn't work out-of-box since it seemed to depend on glibc. So this container definition includes an optional glibc compat library for that reason - it should raise the chances of extensions working unmodified, so it seemed worth including in addition to git.
Anything else that jumps out we should include @chrmarti?
=> Alpine definition

containers/python-3/.devcontainer/Dockerfile, containers/python-3/.devcontainer/devcontainer.json
- Drop an unnecessary `*` at the end of a file name for copying
- Don't have pip bother checking for a newer version of pip (assume it's new enough as it came with the latest version of Python which the container is pulling from)
- Don't cache wheel files (to keep the image smaller)
- Specify the location of the `pylint` executable to turn on Pylint development
=> Tweak Python 3 setup

containers/puppet/.devcontainer/Dockerfile, containers/puppet/.devcontainer/devcontainer.json, containers/puppet/.npmignore, containers/puppet/README.md
This PR adds a [Puppet Development Kit](https://puppet.com/docs/pdk/1.x/pdk.html) docker container to VS Code Remote Container extension. It contains a Dockerfile that uses a base `ruby:2` docker image and installs PDK, git, and Ruby debugging gems.
This allows a user to create and edit Puppet manifests, modules and other code without installing the PDK or other Ruby tools on their machine. The [Puppet VSCode Extension](https://pup.pt/vscode) is included in the defintion to provide advanced intellisense and other IDE capabilties. The Ruby VS Code extension is also included to help with editing Ruby files.
=> Puppet PDK Docker Container file

containers/python-3/.devcontainer/Dockerfile, containers/python-3/.devcontainer/devcontainer.json, containers/python-3/.devcontainer/noop.txt, containers/python-3/README.md
Instead, make it a suggested `postCreateCommand`.
=> Don't run `pip install -r requirements.txt` in the Dockerfile

containers/python-2/.devcontainer/Dockerfile, containers/python-2/.devcontainer/devcontainer.json, containers/python-2/.devcontainer/noop.txt, containers/python-2/README.md, containers/python-3-anaconda/.devcontainer/devcontainer.json, containers/python-3-miniconda/.devcontainer/devcontainer.json, containers/python-3-postgres/.devcontainer/Dockerfile, containers/python-3-postgres/.devcontainer/devcontainer.json, containers/python-3-postgres/.devcontainer/noop.txt, containers/python-3-postgres/.vscode/launch.json, containers/python-3-postgres/.vscode/tasks.json, containers/python-3-postgres/README.md, containers/python-3-postgres/requirements.txt, containers/python-3-postgres/test-project/requirements.txt, containers/python-3/.devcontainer/devcontainer.json
Bring the non-conda containers all in sync in regards to not running pip during container creation and updating their `devcontainer.json` for Pylint. For conda containers, just update `devcontainer.json`.
=> Python updates

containers/sfdx-project/.devcontainer/devcontainer.json
This PR updates the devcontainer.json file to use the settings property to point to the container installed path of java home.  Thanks for help @Chuxel
=> Set java home via settings property

containers/go/.devcontainer/Dockerfile
This saves about 130 megs. Not a huge deal if local but if folks end up
pushing to a registry is nice (~>10% reduction).
=> Add the go src directory to the clean up.

containers/dotnetcore-2.1/.devcontainer/Dockerfile, containers/dotnetcore-2.1/README.md, containers/dotnetcore-2.2/.devcontainer/Dockerfile, containers/dotnetcore-2.2/README.md, containers/dotnetcore-latest/.devcontainer/Dockerfile, containers/dotnetcore-latest/README.md
Resolves #133. 
This PR includes arguments in the Dockerfile that will install Node.js (common need for ASP.NET web apps) and the Azure CLI.
By default, Node.js is installed, but the Azure CLI is not.
READMEs also contain this information.
=> Enable optional installation of Node and the Azure CLI

containers/docker-in-docker-compose/.devcontainer/devcontainer.json, containers/docker-in-docker-compose/README.md, containers/docker-in-docker/.devcontainer/devcontainer.json, containers/docker-in-docker/README.md
The Docker extension defaults to being a workspace extension now so the previous workaround is unnecessary
=> Update Docker-in-Docker templates

containers/docker-in-docker/README.md
Without the `\`, "docker build" will fail since it thinks that `&&` is a directive on its own (instead of being a part of the previous `RUN` directive).
=> docker-in-docker: add missing "\" in README.md

containers/dotnetcore-2.1-fsharp/test-project/app.fsproj, containers/dotnetcore-2.2-fsharp/test-project/app.fsproj, containers/dotnetcore-3.0-fsharp/test-project/app.fsproj
This comes in the shared framework pulled in by the SDK in the project file, so it should be fine to remove. We don't include it in new templates in the .NET SDK.
=> netstandard reference shouldn't be necessary in F# projects

containers/dapr-dotnetcore-3.0/.devcontainer/Dockerfile, containers/dapr-dotnetcore-3.0/.devcontainer/devcontainer.json, containers/dapr-dotnetcore-3.0/.devcontainer/docker-compose.yml, containers/dapr-dotnetcore-3.0/.npmignore, containers/dapr-dotnetcore-3.0/.vscode/launch.json, containers/dapr-dotnetcore-3.0/.vscode/settings.json, containers/dapr-dotnetcore-3.0/.vscode/tasks.json, containers/dapr-dotnetcore-3.0/README.md, containers/dapr-dotnetcore-3.0/test-project/.gitignore, containers/dapr-dotnetcore-3.0/test-project/Controllers/AccountsController.cs, containers/dapr-dotnetcore-3.0/test-project/Program.cs, containers/dapr-dotnetcore-3.0/test-project/Startup.cs, containers/dapr-dotnetcore-3.0/test-project/aspnetapp.csproj
Adds a definition for a dev container for using Dapr with C# & .NET Core 3.0.  This definition combines the definition for C# & .NET Core 3.0 with the Docker in Docker Compose definition, plus installs the latest version of the Dapr CLI (which requires the latter).  When started, the dev container automatically initializes the Dapr runtime, using a separate Docker network to isolate it from the local environment.
=> Add dev container for Dapr with C# & .NET Core 3.0

containers/dapr-dotnetcore-3.0/.devcontainer/Dockerfile, containers/dotnetcore-2.1/.devcontainer/Dockerfile, containers/dotnetcore-2.2/.devcontainer/Dockerfile, containers/dotnetcore-3.0-fsharp/.devcontainer/Dockerfile, containers/dotnetcore-3.0/.devcontainer/Dockerfile
Please propagate this change to the remote dev container extension as well please
=> Fix variable name typo (DOTNETCORE_VESRION -> DOTNETCORE_VERSION)

containers/dapr-dotnetcore-3.0/README.md, containers/dapr-typescript-node-12/.devcontainer/Dockerfile, containers/dapr-typescript-node-12/.devcontainer/devcontainer.json, containers/dapr-typescript-node-12/.devcontainer/docker-compose.yml, containers/dapr-typescript-node-12/.npmignore, containers/dapr-typescript-node-12/.vscode/launch.json, containers/dapr-typescript-node-12/.vscode/settings.json, containers/dapr-typescript-node-12/.vscode/tasks.json, containers/dapr-typescript-node-12/README.md, containers/dapr-typescript-node-12/test-project/.eslintrc.json, containers/dapr-typescript-node-12/test-project/components/redis.yaml, containers/dapr-typescript-node-12/test-project/components/redis_messagebus.yaml, containers/dapr-typescript-node-12/test-project/package-lock.json, containers/dapr-typescript-node-12/test-project/package.json, containers/dapr-typescript-node-12/test-project/src/accounts.ts, containers/dapr-typescript-node-12/test-project/src/daprClient.ts, containers/dapr-typescript-node-12/test-project/src/server.ts, containers/dapr-typescript-node-12/test-project/test.sh, containers/dapr-typescript-node-12/test-project/tsconfig.json, containers/dapr-typescript-node-12/test-project/tslint.json
Adds a definition for a dev container for using Dapr with Node.js 12 and TypeScript. This definition combines the definition for Node.js 12 and TypeScript with the Docker in Docker Compose definition, plus installs the latest version of the Dapr CLI (which requires the latter). When started, the dev container automatically initializes the Dapr runtime, using a separate Docker network to isolate it from the local environment.
This definition is analogous to the definition for [Dapr with C# and .NET Core 3.0](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dapr-dotnetcore-3.0).
=> Add a Dev Container for developing Dapr with Node.js 12 & TypeScript

containers/dapr-dotnetcore-3.0/.devcontainer/docker-compose.yml, containers/dapr-typescript-node-12/.devcontainer/docker-compose.yml
Currently, each Dapr Dev Container for a given platform use a platform-specific Docker network, the thinking being that developers would want a completely isolated Dapr development environment.  However, in multi-service application scenarios, developers are likely to want the services to interact, even if developed across different platforms.
This change makes Dapr Dev Containers use a common Docker network by default, to enable such scenarios without additional configuration.  In practice, even for users *not* requiring interacting services (e.g. those new to Dapr), using a common network likely has no real impact on their development.  (And, if it does the user can always change the configuration to use a unique network.)
=> Use a common Docker network across Dapr Dev Containers.

containers/javascript-node-10/.devcontainer/Dockerfile, containers/javascript-node-12/.devcontainer/Dockerfile
Aqua security is reporting an issue with imagemagick which is in the default Node.js images.  There is not an upstream patch for Debian stretch currently, so remove the package tactically until the Node image is patched or moves to Debian buster which does not have the issue.
More information here: https://security-tracker.debian.org/tracker/CVE-2019-10131
=> Remove imagemagick due to CVE-2019-10131

build/README.md, build/src/prep.js, build/src/utils/config.js
Currently the build tagging process for pre-built images updates dockerfiles to reference the MAJOR.MINOR version of the dev container.  
This is likely too restrictive as a starting point.  This PR updates the build script to instead use just the MAJOR version of the image by default. 
While we could drop the version entirely, this could complicate situations where the image gets out of sync with a breaking update to devcontainer.json.
=> Switch from tagging stubs with MAJOR.MINOR to just MAJOR

containers/javascript-node-10/.devcontainer/Dockerfile, containers/javascript-node-12/.devcontainer/Dockerfile
This PR updates the location of globally installed packages in the containers so `npm install -g` can be used with the `vscode` non-root user without sudo.
=> Use an alternate location for node's global packages

script-library/common-debian.sh, script-library/common-redhat.sh
For example, CVE-2019-13627 has been patched for Ubuntu, but is not in the base Ubuntu image at this moment.
=> Run upgrade when generating images to get security updates not in base image

containers/go/.devcontainer/Dockerfile
This tries to solve the problem of not being able to run go mod init as a non-root-user in the go dev container.
See github [issue](https://github.com/microsoft/vscode-dev-containers/issues/226).
This is my first pull request. Not sure if I am doing it correctly...
=> Added write permission for /go/pkg in go container.

containers/python-3/.devcontainer/Dockerfile
Currently when I am attached to the `python-3` container perform a `git log`, the
command complains that `less` is not available.
So I added it to the same `apt-get` where `git` is installed as well.
=> install `less` to do `git log` without error msg

.github/workflows/cgmanifest.yml, .github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, .vscode/launch.json, .vscode/settings.json, build/src/cgmanifest.js, build/src/package.js, build/src/push.js, build/src/utils/config.js, build/vscdc, package.json
This implements #223. The core build time is now approx 2-3 mins with three "pages" that are built concurrently.  As we onboard more images, we can add more pages to speed things up further. Packaging then happens after all the builds have completed though in concept it could happen in parallel.
The logic uses one level of image dependencies to do the paging so that, if an image depends on another image, the parent image is built first.  This logic does not extend to multiple parents currently. (Parents can't have parents yet, but we have no definitions in this scenario today.)
All of this required some refactoring of the build CLI commands to get working.
cgmanifest.json generation is also automatically triggered once the build completes but as a separate workflow via the …
=> Parallelize image generation to speed up CI process

.github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, .vscode/launch.json, build/src/prep.js, build/vscdc
This PR resolves a current issue where Dockerfiles tied to a release tag do not reference version specific links to common scripts.  The resulting `.tgz` package does, however, so this is not P0.  However, this update makes it easier to reproduce a build from a tag.
One downside of the approach, however, is that it deletes and updates an existing tag to maintain the current workflow where just tagging triggers a release.  As a result, whoever triggers a release will need to do a `git fetch --tags --force` to get the updated tag. Otherwise Git will complain about clobbering an existing local one.
=> Automatically update tags to use version specific script source

build/src/prep.js, build/src/utils/config.js, containers/typescript-node-10/definition-build.json, containers/typescript-node-12/definition-build.json
Implements https://github.com/microsoft/vscode-dev-containers/issues/209 which is required for https://github.com/microsoft/vscode-dev-containers/issues/155 (VS Online image).
This adds a `definitionVersion` property into `definition-build.json` that, if specified, is used for the version of the image that is generated whenever a release is specified.  (Specifying a branch like master still results in the 'dev' version.)
If no `definitionVersion` is specified, the release version is used instead. All current definitions will behave this way since #155 is the first one that would use definition specific versioning and that will be a separate PR.
=> Implement image / dev container specific versioning

containers/azure-functions-dotnetcore-3.1/.devcontainer/Dockerfile
Functions PG recently started pushing the v3 core tools to apt-get so we can pull from there now! :)
=> Change the Functions 3.1 dev container to pull from apt-get

containers/kubernetes-helm/.devcontainer/Dockerfile, containers/kubernetes-helm/README.md
The container template `kubernetes-helm` is still using helm 2. I changed it using helm 3 and deleted the optional steps from the docu where it says to call `helm init` which was needed to setup the tiller in the K8s cluster
=> helm 3 support for kubernetes-helm template

containers/go/.devcontainer/Dockerfile
Installation of the Go tools necessary for VS Code integration
leaves dependency packages in GOPATH (/go).
This leads to two problems:
1. Permission problems when using the image as non-root.
2. Increase of the image size.
This commit fixes both problems by using a throw-away GOPATH
while building the necessary Go tools and moving the resulting
binaries to /usr/local/bin.
Fixes #249
=> Cleanup Go package cache

containers/python-3-postgres/.devcontainer/Dockerfile, containers/python-3-postgres/.devcontainer/devcontainer.json, containers/python-3-postgres/.devcontainer/docker-compose.yml, containers/python-3-postgres/README.md, containers/python-3/README.md
This PR updates the Python 3 & PostgresSQL definition to use the new pre-built Python image.
=> Use pre-built Python images in python-3-postgres

containers/azure-functions-python-3/.devcontainer/Dockerfile, containers/azure-functions-python-3/.devcontainer/devcontainer.json
Turns out there's no need to add the extra apt-get source.
=> Azure Functions Python 3 - Remove unnecessary apt source

.github/workflows/cgmanifest.yml, .github/workflows/patch.yml, .github/workflows/push-and-package.yml, .github/workflows/push-dev.yml
PR switches to a service principal to interact with ACR and enables ACR lookups to see if something is already published. If a version is already published, skip it (though this does not apply to dev tag).
=> Migrate publish to service principal, only update MCR if version updates

containers/php-7-mariadb/.devcontainer/Dockerfile, containers/php-7-mariadb/.devcontainer/devcontainer.json, containers/php-7-mariadb/.devcontainer/docker-compose.yml, containers/php-7-mariadb/.npmignore, containers/php-7-mariadb/.vscode/settings.json, containers/php-7-mariadb/README.md, containers/php-7-mariadb/test-project/test.sh
Add a devcontainer definition for PHP 7 and MariaDB.  This is in response to #253, which requested a PHP and MySQL definition.
This definition is using MariaDB instead of MySQL because it is based off of a configuration I'd already been using, and because the version of default-mysql-client supplied by PHP 7's version of Debian is not compatible with the authentication plugin used by the latest version of MySQL.  The PHP MySQL drivers are also compatible with MariaDB so this shouldn't matter from the PHP side.
=> Add PHP 7 & MariaDB

containers/dapr-dotnetcore-3.1/.devcontainer/devcontainer.json, containers/dapr-typescript-node-12/.devcontainer/devcontainer.json, containers/dapr-typescript-node-12/test-project/components/redis.yaml, containers/dapr-typescript-node-12/test-project/src/accounts.ts, containers/dapr-typescript-node-12/test-project/src/daprClient.ts
Add the Dapr extension as a default remote extension for the Dapr-related templates.  Update the Node.js with Dapr template based on breaking changes in recent Dapr runtimes.
Resolves [vscode-dapr#86](https://github.com/microsoft/vscode-dapr/issues/86).
=> Add Dapr extension to default remote extensions

containers/puppet/.devcontainer/Dockerfile, containers/puppet/.devcontainer/devcontainer.json
This PR updates the VS Code Extension ID from `jpogran.puppet-vscode` to `puppet.puppet-vscode` in the official Puppet namespace.
=> Update Puppet Extension Identifier and Dockerfile

containers/docker-in-docker/README.md
The last part of the command fails due to missing back-slashes
=> Missing multi-line continuation characters

containers/dotnetcore-3.1/.devcontainer/Dockerfile
update nvm install script url to the latest one (listed here: https://github.com/nvm-sh/nvm#install--update-script).
=> dotnetcore-3.1: Update URL to nvm install script

containers/azure-functions-pwsh-6/.devcontainer/Dockerfile
I noticed an issue when using this devcontainer in VS Codespaces. I created a new Functions project and HTTP-triggered function. The functions worker process gets into a bad state, prompting retries from the host, which eventually gives up can exits: `Exceeded language worker restart retry count for runtime:powershell. Shutting down Functions Host`
Making this change to update to v3 fixes the issue.
=> Updating Core Tools to v3 in PS Functions image

containers/azure-functions-java-8/.devcontainer/Dockerfile
Hi @Chuxel 
I update the java8 one with two things. 
* Fix missing URL for the Dockerfile (someone change the URL for the target repo)
* Add comment for the Development Container Script 
Our base image is for Azure Functions Core Tools and Azure CLI.  I wanted to separate the concern. 
I just add the comment for the Development Container Script so that  customer can comment out. 
I also consider if we can do it with a switch instead of the comment. However, it can hit a cache and ignore it. For this reason, I make it as comment. 
Any feedback is welcome.
=> Fix missing URL and update comment Development Container Script

containers/azure-functions-dotnetcore-3.1/.devcontainer/Dockerfile, containers/azure-functions-node-10/.devcontainer/Dockerfile, containers/azure-functions-node-12/.devcontainer/Dockerfile, containers/azure-functions-python-3/.devcontainer/Dockerfile
Hi @Chuxel , 
I published the following Azure Functions images. So I switch to the Azure Functions Docker images. 
* Dotnet Core 3.1
* Node 10
* Node 12
* Python 3.8
These images are tested by running the Readme process.  (Open the DevContainer then, create project, then debug run. check if the break point works if I send a request). 
I also add a comment of  Development Container Script. It is the same as the Java one.  
https://github.com/microsoft/vscode-dev-containers/pull/332
=> Move Azure Functions container to Azure Functions Official Images

containers/puppet/.devcontainer/devcontainer.json
This PR removes the reference to the vscode user from the devcontainer, as the [`puppet/pdk`](https://github.com/puppetlabs/pdk-docker/blob/cc4ff84497432057d4ae4a5b2e8f45206b26f4e7/Dockerfile) docker image does not have such a user.
At the time of this commit, the [`puppet/pdk`](https://github.com/puppetlabs/pdk-docker/blob/cc4ff84497432057d4ae4a5b2e8f45206b26f4e7/Dockerfile) image does not create a
non-root user. If/when it does, this can be re-added.
=> Remove vscode user from Puppet devcontainer

container-templates/docker-compose/.devcontainer/devcontainer.json
Fix a typo.
Keep instructions about commented properties consistent.
=> Fix Comments in docker-compose devcontainer.json

containers/java-11/.devcontainer/Dockerfile
This PR fixes errors such as the one below:
```
LC_ALL: cannot change locale (en_US.UTF-8)
```
The PR also brings the Dockerfile towards the standardize convention of using common-debian.sh for all docker images based on the debian images.
=> Java11 Dockerfile to use common-debian

containers/docker-in-docker/README.md
I walked through this tutorial and found that this sample code did not work for me.
`*.socket` should have been `*.sock` 
and
Line 83 is actually ensuring that the `docker-host.sock` file exists before creating a symbolic link.
and
Line 90 is actually removing the symbolic link created above if that script gets executed. `sudo socat` will fail if `docker.sock` already exist.s
Let me know if this is incorrect.
I did not test out the other scenarios (docker compose + kubernetes).
=> Non-root Docker in Docker README changes

containers/python-3/.devcontainer/base.Dockerfile
A temporary copy of pipx can result in missing dependencies when installing other packages (in this case `black`). Force reinstalling resolves the problem.
=> Resolve #361

repository-containers/github.com/tensorflow/addons/.devcontainer/Dockerfile, repository-containers/github.com/tensorflow/addons/.devcontainer/devcontainer.json
Add support to Tensorflow addons:
See https://github.com/tensorflow/addons/pull/1309 and https://github.com/tensorflow/addons/pull/1888
=> Tensorflow addons

repository-containers/github.com/tensorflow/tensorflow/.devcontainer/Dockerfile, repository-containers/github.com/tensorflow/tensorflow/.devcontainer/devcontainer.json
=> Tensorflow devcontainer

containers/dapr-dotnetcore-3.1/.devcontainer/Dockerfile, containers/dotnetcore-fsharp/.devcontainer/Dockerfile, containers/dotnetcore/.devcontainer/Dockerfile, containers/javascript-node-10/.devcontainer/Dockerfile, containers/javascript-node-12/.devcontainer/Dockerfile, containers/javascript-node-14/.devcontainer/Dockerfile
Ensures Node.js installed by NVM works from VS Code tasks, not just the terminal by adding a "current" symlink and adding it to the path.
=> Work around https://github.com/microsoft/vscode-remote-release/issues/3224

containers/bash/.devcontainer/Dockerfile, containers/bash/.devcontainer/devcontainer.json, containers/bash/.vscode/launch.json, containers/bash/README.md
Adds a configuration for Bash development for #254. Included Bash IDE and Bash Debug extensions.
=> Add devcontainer for Bash

containers/vue/.devcontainer/Dockerfile, containers/vue/.devcontainer/devcontainer.json, containers/vue/.npmignore, containers/vue/.vscode/tasks.json, containers/vue/README.md
This adds a config for Vue.js using a node image. 
@Chuxel I debated running the same image from the others and rolling in node, but not sure thats any more efficent, or do you think I should copy the javascript-node-14 config and add in the Vue install?
=> Add Devcontainer for Vue.js

containers/python-3/.devcontainer/base.Dockerfile
The expected commented lines in the RUN command for installing requirements were missing, so I've added them.
=> Add commented option of embedding python project requirements into image

containers/python-3/.devcontainer/Dockerfile, containers/python-3/.devcontainer/base.Dockerfile, containers/vue/.devcontainer/Dockerfile, containers/vue/.devcontainer/devcontainer.json
I just merged in #399 which consolidates the node 10, 12, 14 definitions into one with a build arg. This updates Vue to use the same pattern.
I also noticed that the vue CLI was installed globally as root, which can cause problems with caching, so I prefixed that with `sudo -u node`.
LMK if it looks good @AarynSmith
=> Update Vue definition to match consolidated javascript-node definition, fix non-root scenario

containers/python-3/.devcontainer/Dockerfile, containers/python-3/.devcontainer/base.Dockerfile, containers/python-3/README.md
Related to #409
With Codespaces, more people are looking at the `base.Dockerfile` in this repository since it does not yet have the "Add" experience the Remote - Containers extension has. As a result, I'm going through and doing some simplification and layer refinement. 
For Python, this:
1. Breaks out the pipx install section so that you can add tools to it without re-running the common setup script
2. Removes the giant comment about adding multiple images and adds this to the README instead.
3. Misc other cleanup
=> Simplify Python 3 base.Dockerfile 

containers/hugo/.devcontainer/Dockerfile
Apparently there was a bug with running hugo-extended in alpine containers. I thought it was working, but it wasn't. 
This PR switches from alpine to the base versions to resolve it.
=> Fix error with hugo container

containers/go/.devcontainer/Dockerfile
When installing tools, install them individuallly rather than
with one single `go get` command. Otherwise, the go command
runs MVS for all the listed tools and builds each tool with
unexpected dependencies.
See https://github.com/golang/vscode-go/issues/363#issuecomment-660335139
Also, remove gometalinter - vscode-go no longer uses it.
GO111MODULE=auto is perfectly fine. If `go.mod` exists
in the repo, the go command will automatically switch to the
modules mode. Unsetting is also fine but I will leave it as it is.
=> containers/go: correct tools installation in modules mode

containers/codespaces-linux/.devcontainer/Dockerfile, containers/codespaces-linux/.devcontainer/symlinkDotNetCore.sh, containers/codespaces-linux/definition-manifest.json
Update to latest oryx, that includes .Net Core 3.1.302 as per https://github.com/microsoft/vscode-dev-containers/issues/398
Also updates the corresponding symlink file.
=> Update oryx image and symlink to newest version.

containers/go/.devcontainer/Dockerfile, containers/go/.devcontainer/devcontainer.json, containers/go/README.md
This PR is part of #409 and related to #375. It does a few things to the Go definition:
1. Switches it to using the common script used in other definitions that installs common utilities and creates the vscode non-root user.
2. Separates out the installation of the Go tools into a separate layer so that any modifications will not require a re-run of the common script while still ensuring each layer cleans up before moving to the next step.
3. Uses xargs to simplify the code that installs all the different Go tools.
4. Adds comments at the end of the Dockerfile about adding your own `RUN` statements for additional installed contents.
5. Adds a build arg that allows you to specify the Go version from devcontainer.json
For #375, we would just need to trim the list in the …
=> Update Go definition to use common script, two layers, simplify a bit

containers/codespaces-linux/.devcontainer/symlinkDotNetCore.sh
Newer .NET Core SDKs have multiple versions of packages under various subdirectories like `./packs`, so our previous checks for a specific sdk or runtime version were missing some directories that needed to be symlinked.
This update makes the symlinking more generic to symlink all subdirectories that look like a three-segment version number.
I've tested this update manually and it fixes the .NET Core installations under /home/codespace/.dotnet, and OmniSharp intellisense is working again.
Before:
```
codespace:/opt/dotnet/sdks/3.1.301$ find . -name "3.1.301" -o -name "3.1.5"
./host/fxr/3.1.5
./packs/Microsoft.NETCore.App.Host.linux-x64/3.1.5
./shared/Microsoft.NETCore.App/3.1.5
./shared/Microsoft.AspNetCore.App/3.1.5
./sdk/3.1.301
```
After:
```
codespace:/opt/dotnet/sdks/3.1.301$ find . …
```
=> Fix symlinking script for .NET Core installations

containers/codespaces-linux/.devcontainer/symlinkDotNetCore.sh
.NET Core 2.2.402 has some extra directories with version numbers in them, so include `-maxdepth 3` to avoid them.
=> Fix symlinking for .NET Core 2.2.402

containers/kubernetes-helm/.devcontainer/Dockerfile, containers/kubernetes-helm/README.md
Signed-off-by: Aisuko <urakiny@gmail.com>
fix #442 
The PR changed the `localhost` to `127.0.0.1` which the condition includes the `Copy localhost's ~/.kube/config file into the container` script. It looks like no reason but I try to test and will show the result.
```
minikube start or kind create cluster
kubectl config view
```
The all of the config like 
```
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: DATA+OMITTED
server: https://127.0.0.1:61531
name: kind-kind
contexts:
- context:
cluster: kind-kind
user: kind-kind
name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
user:
client-certificate-data: REDACTED
client-key-data: REDACTED
```
|Result|kind@v0.8.1|minikube@v1.12.1(mac)/v1.11.1(ubuntu20.04)|
|:---:|:---:|:---:| …
=> Fixing the api-server URL condition mistakes

containers/jekyll/.devcontainer/Dockerfile, containers/jekyll/.devcontainer/devcontainer.json
Now after cloning https://github.com/azure/azure-sdk running: 
```bash
bundle install
bundle exec jekyll serve --livereload
```
will allow to build and navigate through the site without issues.
=> added locales and forwarded port fixing #436

containers/codespaces-linux/.devcontainer/Dockerfile
We had a [user report](https://github.com/MicrosoftDocs/vscodespaces/issues/644) that they were unable to install `ca-certificates` due to conflicting `apt` sources in the Oryx image. I filed an issue with Oryx but I'm not sure how long it'll take for them to fix it so this is the fix in the meantime.
=> Remove buster source list from VSCS image

containers/azure-cli/.devcontainer/Dockerfile, containers/azure-cli/.devcontainer/library-scripts/README.md, containers/azure-cli/.devcontainer/library-scripts/common-debian.sh, containers/azure-cli/.npmignore, containers/bazel/.devcontainer/Dockerfile, containers/bazel/.devcontainer/devcontainer.json, containers/bazel/.devcontainer/library-scripts/README.md, containers/bazel/.devcontainer/library-scripts/common-debian.sh, containers/bazel/.npmignore, containers/bazel/README.md, containers/perl/.devcontainer/Dockerfile, containers/perl/.devcontainer/devcontainer.json, containers/perl/.devcontainer/library-scripts/README.md, containers/perl/.devcontainer/library-scripts/common-debian.sh, containers/perl/.npmignore, containers/perl/README.md, containers/r/.devcontainer/Dockerfile, containers/r/.devcontainer/devcontainer.json, containers/r/.devcontainer/library-scripts/README.md, containers/r/.devcontainer/library-scripts/common-debian.sh, containers/r/.npmignore, containers/rust/.devcontainer/Dockerfile, containers/rust/.devcontainer/devcontainer.json, containers/rust/.devcontainer/library-scripts/README.md, containers/rust/.devcontainer/library-scripts/common-debian.sh, containers/rust/.npmignore
This PR is part of a repository cleanup to move towards using scripts for installing common dependencies and improve layering.
Reference: #409, #462, #154
//cc: @kmehant @Shikanime - FYI given this affects definitions you contributed. Let me know if you have any concerns.
=> Update rust, bazel, perl, azure-cli, R definitions to use common scripts

containers/azure-functions-java-8/.devcontainer/Dockerfile, containers/azure-functions-java-8/.devcontainer/devcontainer.json
Fix: https://github.com/microsoft/vscode-dev-containers/issues/459
VSCode Java extension requires Java 11 for the extension. 
I update the image to install not only Java 11 but also Java 8
I tested it with deploying Functions App with java8. 
Hi @Chuxel, @anthonychu , and @amamounelsayed  could you have a look? 
This is a quick fix. For supporting java 8, A lot of people using Java 8.  
I'll also provide java 11 soon.
=> fix: VS code java extension requires java 11

containers/jekyll/.devcontainer/Dockerfile, containers/jekyll/.devcontainer/devcontainer.json, containers/ruby-rails/.devcontainer/Dockerfile, containers/ruby-rails/.devcontainer/devcontainer.json, containers/ruby-sinatra/.devcontainer/Dockerfile, containers/ruby-sinatra/.devcontainer/devcontainer.json, containers/ruby/.devcontainer/Dockerfile
This PR switches the RoR, Ruby Sinatra, and Jekyll definitions to use the pre-built MCR Ruby image that contains most of what the Dockerfiles in these definitions added. This is related to #154 
//cc: @cmendible as FYI
=> Update Ruby-based definitions to use new pre-built dev containers Ruby definition

containers/azure-ansible/.devcontainer/Dockerfile, containers/azure-ansible/.devcontainer/devcontainer.json, containers/azure-ansible/.devcontainer/library-scripts/README.md, containers/azure-ansible/.devcontainer/library-scripts/common-debian.sh, containers/azure-ansible/.devcontainer/library-scripts/docker-debian.sh, containers/azure-ansible/.devcontainer/library-scripts/node-debian.sh, containers/azure-ansible/.npmignore, containers/azure-ansible/README.md, containers/azure-terraform/.devcontainer/devcontainer.json, containers/azure-terraform/.npmignore
This is similar to #461 but this time for `azure-ansible`. The update adds `ARG`s to allow people to select what to install/not install from `devcontainer.json` and switches the definition to use common scripts to simplify future maintenance.
@cmendible - Let me know if this looks good to merge to you.
=> Update azure-ansible to use common scripts

containers/azure-functions-java-11/.devcontainer/Dockerfile, containers/azure-functions-java-11/.devcontainer/devcontainer.json, containers/azure-functions-java-11/.devcontainer/maven-settings.xml, containers/azure-functions-java-11/.npmignore, containers/azure-functions-java-11/README.md
https://github.com/microsoft/vscode-dev-containers/issues/459
This is the Java Functions Container for Java 11. 
I tested, it works. 
We need to wait until the end of this month.  VSCode Azure Functions extension will estimated that they will support it at the end of this month. 
https://github.com/microsoft/vscode-azurefunctions/issues/2033
Until then, we can use Azure Functions Core Tools to create/deploy the functions. 
For more details, refer to [Quickstart: Create a function in Azure that responds to HTTP requests](
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function-azure-cli?tabs=bash%2Cbrowser&pivots=programming-language-java)
=> Azure Functions Java 11 DevContainer

script-library/docker-debian.sh, script-library/docker-redhat.sh
The exec replaces the current process with the new process, so we don't have yet another process running in the process tree.
=> Prevent docker scripts to spawn yet another process

NOTICE.txt, containers/java/.devcontainer/Dockerfile, containers/java/.devcontainer/base.Dockerfile, containers/java/.devcontainer/devcontainer.json, containers/java/.devcontainer/library-scripts/gradle-debian.sh, containers/java/.devcontainer/library-scripts/maven-debian.sh, containers/java/.npmignore, containers/java/README.md, containers/java/definition-manifest.json, script-library/maven-debian.sh
This PR on-boards the java container into the image build process and is part of work for #154.
Currently it will output the following image variants for Java versions:
```
mcr.microsoft.com/vscode/devcontainers/java:11
mcr.microsoft.com/vscode/devcontainers/java:14
```
...based on the [contents of `base.Dockerfile`](https://github.com/microsoft/vscode-dev-containers/blob/clantz/onboard-java/containers/java/.devcontainer/base.Dockerfile). 
Note that we generally we drop no longer supported versions of Java from the build process once the version is out of support. However, existing tags, just with an older image. 
**Note that this does not include Java 8** because the Java extension seems to require it be set to Java home, and there appears to be no good way with symlinks to get this to …
=> Onboard java to build

containers/python-3/.devcontainer/Dockerfile, containers/python-3/.devcontainer/base.Dockerfile, containers/python-3/.devcontainer/devcontainer.json, containers/python-3/.devcontainer/library-scripts/node-debian.sh, containers/python-3/README.md
"How do I add node" is a common question for images here that are used frequently with web-based development.  This PR adds nvm to the Python base image and an optional arg to install Node.js using it as a part of #470.
=> Add nvm to Python image

containers/bash/.devcontainer/Dockerfile, containers/bash/.devcontainer/devcontainer.json, containers/bash/README.md
Updates the bash definition to use a choice of Debian / Ubuntu to ensure it works in GitHub Codespaces - technically could set variant to "alpine" as well.
//cc: @AarynSmith given you contributed the definition
=> Move bash definition to Debian/Ubuntu

.github/workflows/push-dev.yml, NOTICE.txt, containers/python-3-anaconda/.devcontainer/Dockerfile, containers/python-3-anaconda/.devcontainer/base.Dockerfile, containers/python-3-anaconda/.devcontainer/devcontainer.json, containers/python-3-anaconda/.devcontainer/library-scripts/node-debian.sh, containers/python-3-anaconda/README.md, containers/python-3-anaconda/definition-manifest.json, containers/python-3-miniconda/.devcontainer/Dockerfile, containers/python-3-miniconda/.devcontainer/base.Dockerfile, containers/python-3-miniconda/.devcontainer/devcontainer.json, containers/python-3-miniconda/.devcontainer/library-scripts/node-debian.sh, containers/python-3-miniconda/.devcontainer/library-scripts/python-debian.sh, containers/python-3-miniconda/README.md, containers/python-3-miniconda/definition-manifest.json, containers/python-3/README.md
This updates the Anaconda and Miniconda definitions to mirror Python and adds them to the image build as a part of #154.
Two notes:
- `.devcontainer/devcontainer.json` will be updated to use `Dockerfile` once a dev image exists.
- The added contents of the `library-scripts` folder are automatically updated from `/script-library` in this repo, so they can generally be assumed to work.
This should also resolve #166.
=> Onboard Anaconda and Miniconda to image build

containers/php-mariadb/.devcontainer/docker-compose.yml
Fixes a DB typo in the comments 😉
=> Typo "MongoDB" -> "MariaDB"

script-library/README.md
This way is simpler (at least for passing parameters) + safer. That's why Homebrew suggests this way (https://brew.sh/).
=> Use bash -c instead of piping in the script-library docs

containers/python-3-postgres/.devcontainer/docker-compose.yml
The goal of this PR is to make a superfluous change in the python 3 postgres container docker-compose.yml.
Currently, the docker-compose.yml file notes:
`# Add "forwardPorts": ["5432"] to **devcontainer.json** to forward MongoDB locally` 
The proposed change simply adjusts `MongoDB` to `PostgreSQL` and strips trailing whitespace throughout `docker-compose.yml`.
=> Fix inappropriate MongoDB reference in favor of PSQL

containers/julia/.devcontainer/devcontainer.json, containers/julia/.npmignore, containers/julia/README.md, containers/julia/test-project/test.sh
I don't understand the testing infrastructure, so I just left the test script from the template in here. Should I delete that, or do something else with it?
=> Add Julia devcontainer

script-library/desktop-lite-debian.sh
See https://github.com/koalaman/shellcheck/wiki/SC2054 for background. Seems like a reasonable complaint.
=> Fix schellcheck warning in Debian desktop script

script-library/docs/desktop-lite.md
I was honestly not sure what a "web based desktop viewer" exactly meant given that instructions are also talking about VNC in the same context, but it did turn out to be just a normal web browser.
=> Clarify terminology for Debian Lite

script-library/common-debian.sh
This is a better approach, since using alias does not make it work when `code` is called by CLIs, such as `git` or `gh`.
PS: this does not take precedence over the normal `code` binary, so it's harmless when it's not useful. See:
```sh-session
$ which -a code
/home/vscode/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/bin/code
/usr/local/bin/code
```
References https://github.com/MicrosoftDocs/vscodespaces/issues/809.
=> Use code as shim instead of as an alias

containers/php-mariadb/README.md
Fix a typo, and remove a paragraph present twice
=> Fix typo in php-mariadb's README.md

containers/codespaces-linux/.devcontainer/base.Dockerfile
This PR simply installs the `libsecret-1-dev` package in the universal image, which ensures that common app scenarios work without any further modification (e.g. Node apps that depend on `keytar`). Without this, developers that are using macOS might be surprised to see that their environment no longer works, because they aren't used to the extra requirements for Linux.
=> [Codespaces] Installing libsecret-1-dev by default

containers/codespaces-linux/.devcontainer/library-scripts/sshd-debian.sh, containers/codespaces-linux/definition-manifest.json, script-library/sshd-debian.sh
pid file of the sshd server gets saved in the container. When it is restarted on a different VM, the pid is different and that process gets killed.
This results in random process kills and failure of about 10% of the resumes.
Fix is to change "restart" to "start" so that no process gets killed as container doesn't have any processes at that time.
=> chore: changing "restart" to "start" of sshd server

containers/julia/.npmignore
I believe the current paths in there are the reason while files are copied into user repositories that shouldn't really be copied.
=> Fix paths in .npmignore for Julia

containers/julia/.devcontainer/devcontainer.json
This significantly simplifies the template for Julia by moving all the code that we had here in the template into a Julia script file that is part of the julia-devcontainer docker image. This also makes it very easy for us to update that post create script without having to update anything here in this repo.
You can see the content of `postcreate.jl` [here](https://github.com/julia-vscode/julia-devcontainer/blob/master/postcreate.jl). It is already a bit richer than what we have here currently, and I expect that it will get better as we move forward.
The docker file now copies that file into the `julia-devcontainer`, see [here](https://github.com/julia-vscode/julia-devcontainer/blob/1b95bb98456f8bd6bd491ec4cb931dcbdf501ac7/Dockerfile#L33).
I think this is all getting very, very close to …
=> Move Julia post create commands into the image

containers/jekyll/.devcontainer/Dockerfile, containers/jekyll/.devcontainer/devcontainer.json, containers/jekyll/.devcontainer/post-create.sh, containers/jekyll/README.md
This PR contains a few updates to the Jekyll container
1. If there's a Gemfile, do not install Jekyll by default. Doing that would automatically install the latest version, which may or may not be what the user wants. Instead, run `bundle install` in the post-create step. If there's no Gemfile, then installs jekyll in the post-create step. This should be a compromise for #447 
2. Adding live reload server port to the list of ports (for `jekyll serve -l`)
3. Updated default time zone to a more universal Etc/UTC
=> Updates to Jekyll container

containers/hugo/.devcontainer/Dockerfile, containers/hugo/.devcontainer/devcontainer.json, containers/hugo/.vscode/tasks.json, containers/hugo/README.md
1. Re-basing this to the Node.js container because that can be very useful to build themes (note: this container does not include Go just like the old container didn't - I don't believe this is necessary when working with Hugo).
2. Removed a command that was patching the binary. That is not necessary when not running on Alpine (the container runs on Debian)
3. The downloaded binary is always called `hugo` (even in extended mode), so changed `mv hugo*` to `mv hugo` to be on the safer side
4. Disabled problem matchers in tasks.json
=> Changes to the Hugo container

containers/dotnet/README.md
Updated the **containers/dotnetcore** folder to containers/dotnet.
Also, in VS Code 1.51.1, I did not see the **Remote-Containers: Forward Port from Container** option so I updated the steps there as well. See below:
=> Update containers/dotnet readme

containers/codespaces-linux/.devcontainer/devcontainer.json
As illustrated [in the Oryx repo](https://github.com/microsoft/Oryx/blob/1a35fbce482b20b71290f3a837a3469803ce4b44/src/BuildScriptGenerator/Python/PythonPlatform.cs#L547) you can set the python venv manually.  Fixes [public feedback](https://github.community/t/codespace-doesnt-handle-python-venv-properly/137691) and an internal issue referring to venv naming being unintuitive in codespaces.
=> [Codespaces] Manually set the name oryx uses for python venv

containers/codespaces-linux/.devcontainer/base.Dockerfile
npm places symlink of installed tools to `{prefix}/bin`.
Reference: https://docs.npmjs.com/cli/v6/configuring-npm/folders#executables
=> codespaces-linux: fix PATH for npm

script-library/common-debian.sh
Now it only looks for `code` down in the PATH, preventing an infinite loop.
=> Fix code binary when it also exists in dotfiles

containers/go/.devcontainer/base.Dockerfile, containers/go/.devcontainer/devcontainer.json, containers/go/.devcontainer/library-scripts/common-debian.sh, containers/go/.devcontainer/library-scripts/go-debian.sh, containers/go/.devcontainer/library-scripts/node-debian.sh, containers/go/README.md, containers/go/definition-manifest.json, containers/go/test-project/hello.go
This PR:
* Removes trailing whitespace from config files to reduce future diff sizes (many editors automatically remove trailing whitespace).
* Formats Go code with `gofmt`.
There are no functional changes.
=> Tidy up whitespace in Go dev container

repository-containers/github.com/terraform-providers/terraform-provider-azurerm/.devcontainer/Dockerfile
Using golang 1.15 as defined in the provider developer checklist
https://github.com/terraform-providers/terraform-provider-azurerm#developer-requirements
=> Using golang 1.15

containers/dotnet-fsharp/.devcontainer/Dockerfile, containers/dotnet-fsharp/.devcontainer/devcontainer.json, containers/dotnet-fsharp/test-project/Program.fs, containers/dotnet-fsharp/test-project/app.fsproj
The latest Ionide plugin (5.x) requires the .NET 5 SDK. F# developers also tend to update things very quickly, so I think we can just drop the other .NET Core SDK options. Otherwise, to make this function with the other SDKs, we'd have to install specific versions of the plugin.
=> Update F# to use .NET 5 only

containers/javascript-node-postgres/test-project/package.json
Underlying pg library doesn't work on node 14 with this pg-promise version. Needs pg-promise bump to fix this: https://github.com/brianc/node-postgres/issues/2180
=> Bump pg-promise version

script-library/docker-in-docker-debian.sh
Fixes: https://github.com/microsoft/vssaas-planning/issues/2499
This DNS address was taken from: 
https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#considerations
> The Azure DNS IP address is 168.63.129.16. This is a static IP address and will not change.
=> hardcode azure dns for docker daemon in docker-in-docker

containers/elm/.devcontainer/Dockerfile, containers/elm/.devcontainer/devcontainer.json
See these issues for the problems with the new version of ELS:
elm-tooling/elm-language-server#461
elm-tooling/elm-language-server#457
This solves it through configuration. I added a pretty huge comment, let me know if instead I should maybe make it shorter and link to these issues or something like that? Or if I could phrase anything better? Most of my progress in thoughts and discussion about how best to handle this can be found in elm-tooling/elm-language-server#461 
Have a good day!
1. On current master, open the elm folder here in the dev container, go to the HelloWorld.elm file and let ELS load, try hovering over something etc. You can verify that an `elm-stuff` folder should now have been created in the test-project directory
2. Run the rebuild container command that comes with the …
=> Fix ELS crashing through config

containers/javascript-node-postgres/.devcontainer/docker-compose.yml
Just replaced _MongoDB_ with _PostgreSQL_ in a comment line
=> Fix comment referring to MongoDB

containers/codespaces-linux-stretch/.devcontainer/devcontainer.json, containers/codespaces-linux/.devcontainer/devcontainer.json, containers/go/.devcontainer/devcontainer.json, repository-containers/github.com/terraform-providers/terraform-provider-azurerm/.devcontainer/devcontainer.json, script-library/go-debian.sh
Reduce the number of pre-installed go tools - gopls is the
default language feature provider for golang.go since its
v0.22.0, so preinstall only the required tools with the
default settings. For additional tools, the extension will
prompt users to install when necessary.
Also, clean up devcontainer's go extension settings.
Some gopls settings are outdated. Some [go] settings are
unnecessary because the extension sets them up by default,
and the gopls update setting is now obsolete.
=> update go container build script and devcontainer.json

containers/azure-terraform/.devcontainer/Dockerfile, containers/azure-terraform/.devcontainer/devcontainer.json, containers/azure-terraform/.devcontainer/library-scripts/terraform-debian.sh, containers/azure-terraform/README.md
Proposed change is to include [Terragrunt](https://github.com/gruntwork-io/terragrunt) in the Azure Terraform definition.
> Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple Terraform modules.
How I tested it: opened the `containers/azure-terraform` in VSCode and ran "Reopen in Container".
Once container started, I confirmed Terragrunt was installed:
I realize not everyone uses Terragrunt, so possibly we can set
```json
// containers/azure-terraform/.devcontainer/devcontainer.json
...
"args": {
...
"TERRAGRUNT_VERSION": "none",
}
```
to not have it installed by default. If a developer wants to use it, they will have to change the argument to either a specific version or to `latest`.
=> Add Terragrunt to Azure Terraform definition

script-library/docker-in-docker-debian.sh
When the docker-init is written to file an unescape variable will be evaluated.  This causes the `$?` to always evaluate to its first value.
=> need to escape variables in docker-init script template

containers/alpine/.devcontainer/Dockerfile, containers/alpine/.devcontainer/base.Dockerfile, containers/alpine/.devcontainer/devcontainer.json, containers/alpine/README.md, containers/alpine/definition-manifest.json, containers/go/.devcontainer/Dockerfile, containers/go/.devcontainer/base.Dockerfile, containers/go/.devcontainer/devcontainer.json, containers/go/definition-manifest.json
Go 1.16 is out, so we can now build it. 1.14 is no longer receiving security patches, so that image version is now deprecated.
Alpine 3.13 is out, but 3.10 is not yet out of support, so this is just an addition.
=> Updates for new versions of Go, Alpine

containers/r/.devcontainer/Dockerfile, containers/r/.devcontainer/devcontainer.json, containers/r/README.md
This pull request updates R to latest version and add [`vscode-R`](https://github.com/Ikuyadeu/vscode-R) recommended settings.
- Change base image `rocker/r-apt:bionic`(R 3.6.3) to [`rocker/r-ver`](https://github.com/rocker-org/rocker-versioned2), which provide specific version R (4.0.0 ~ 4.0.4) based on Ubuntu LTS.
- Change not to install `libzip-dev`. (`libzip-dev` was needed for [R Tools](https://github.com/MikhailArkhipov/vscode-r) #60, which is not included by #473 ).
- Install `libxt-dev`, for to plot without warning.
- Add vscode-R recommended settings and packages.
- Install [`R LSP Client`](https://github.com/REditorSupport/vscode-r-lsp) and [`R Language Server`](https://github.com/REditorSupport/languageserver).
- Install `libcurl4-openssl-dev`, `libssl-dev`, `libxml2-dev`, for …
=> Update R Docker image and vscode-r recommended settings

script-library/common-alpine.sh, script-library/common-debian.sh, script-library/common-redhat.sh, script-library/docs/common.md
This PR moves away from using Oh My Bash! by default and replaces it with a PS1 script that does exactly what the default prompt did.  This should resolve conflicts described in #674 and drop a dependency.  The Python extension's prefixing should also work by default with this update.
A stub script is left in the image under `~/.oh-my-bash/oh-my-bash.sh` that lets people know this has happened in the event OMB is referenced in their `dotfiles` and by extension their `~/.bashrc` or `~/.bash_profile` files.
The only downside with doing this is you need to remove the folder before installing OMB if you want it. At the moment its erroring on the side of awareness despite that fact.  I expect that after a few months we can remove this stub.
//cc: @matthewisabel @lostintangent @bamurtaugh
=> Sunset Oh My Bash

containers/alpine/definition-manifest.json, containers/codespaces-linux-stretch/definition-manifest.json, containers/codespaces-linux/definition-manifest.json, containers/cpp/definition-manifest.json, containers/debian/definition-manifest.json, containers/dotnet/definition-manifest.json, containers/go/definition-manifest.json, containers/java-8/definition-manifest.json, containers/java/definition-manifest.json, containers/javascript-node/definition-manifest.json, containers/php/definition-manifest.json, containers/python-3-anaconda/definition-manifest.json, containers/python-3-miniconda/definition-manifest.json, containers/python-3/definition-manifest.json, containers/ruby/definition-manifest.json, containers/ubuntu/definition-manifest.json
This PR updates the version number for all images to:
1. Pick up the OMB sunset changes
2. Prepare for the VS Code release to stable where we want to get images to "current" including security patches
CC'ing others in case there's something else we think needs to get in before in the mean time.
=> Bump image version numbers for VS Code release, OMB sunset

script-library/docs/python.md
I found a super-minor issue in the python.md when reading it to setup a dev environment.  In a previous change, the line after the `RUN apt-get update && bash /tmp/library-scripts/python-debian.sh "3.8.3" "${PYTHON_PATH}" "${PIPX_HOME}" \ ` was removed, but the `\` was left.  If someone is copy-pasting to play with it, they'll get an error because of it.
=> Minor doc fix for python install script

script-library/README.md, script-library/docs/homebrew.md, script-library/homebrew-debian.sh, script-library/test/run-scripts.sh
This PR adds a Homebrew installation script in the script library.
The installation is performed using [the official instructions](https://docs.brew.sh/Homebrew-on-Linux) and [Homebrew CI Docker containers](https://github.com/Homebrew/brew/blob/master/Dockerfile) as references.
Additionally, this script allows installing a shallow cloned copy of Homebrew, which is lightweight but fixes the package index in stone. This useful if you're creating a lot of dev containers based on slightly different versions of upstream images (for example, different versions of `node` for a bunch of microservices) allowing you to save GBs of local storage.
Related: https://github.com/microsoft/vscode-dev-containers/issues/357
=> Add Homebrew install script to the script library

containers/azure-terraform/.devcontainer/library-scripts/terraform-debian.sh, script-library/terraform-debian.sh
Context: a month ago I created a pull request that added **Terragrunt support to the Azure Terraform definition**: https://github.com/microsoft/vscode-dev-containers/pull/737
I've just realized I made a **mistake**. My bad I've updated the code in `containers/azure-terraform/.devcontainer/library-scripts/terraform-debian.sh` **but not in** `script-library/terraform-debian.sh`. 
Recent automated updates to the script library **overwrote my changes**: https://github.com/microsoft/vscode-dev-containers/commits/master/containers/azure-terraform/.devcontainer/library-scripts/terraform-debian.sh
Currently Azure Terraform definition is **inconsistent**: `devcontainer.json` and `Dockerfile` mention Terragrunt, but it's not supported by `terraform-debian.sh`.
This pull request fixes the problem by …
=> Bugfix: Restore Terragrunt in Azure Terraform definition

containers/codespaces-linux/.devcontainer/base.Dockerfile, containers/codespaces-linux/.devcontainer/first-run-notice.txt, containers/codespaces-linux/.devcontainer/setup-user.sh, containers/codespaces-linux/definition-manifest.json
Re: https://github.com/github/codespaces/issues/2511
The text is now externalized in a file, so anyone can tweak or make suggestions in the PR.  Right now the aka.ms link points to the codepsaces-linux definition since I don't think there's anywhere else. We can update the link if we get something into docs.
/cc: @2percentsilk @bailey @matthewisabel @jkeech
=> Update welcome text for codespaces-linux

containers/codespaces-linux/.devcontainer/base.Dockerfile, containers/codespaces-linux/.devcontainer/devcontainer.json, containers/codespaces-linux/definition-manifest.json
closes https://github.com/microsoft/vssaas-planning/issues/1813
closes https://github.com/microsoft/vssaas-planning/issues/1982
Bumps oryx version, fixing some python scenarios.
=> [codespaces] bump oryx to 20210319.1

containers/codespaces-linux/.devcontainer/base.Dockerfile, containers/ruby-rails/.devcontainer/Dockerfile, containers/ruby-rails/README.md
Fixes: https://github.com/microsoft/vssaas-planning/issues/755
Adds in the PFS domain as an environment variable to unblock ruby on rails developers on the codespaces-linux image.
Rails docs:
https://edgeguides.rubyonrails.org/configuring.html#configuring-middleware
=> [codespaces] supply PFS domain to allow domain through during ruby development

containers/python-3-anaconda/.devcontainer/devcontainer.json, containers/python-3-device-simulator-express/.devcontainer/devcontainer.json, containers/python-3-miniconda/.devcontainer/devcontainer.json, containers/python-3-postgres/.devcontainer/devcontainer.json, containers/python-3/.devcontainer/devcontainer.json
This fixes #723 
- Add `"ms-python.vscode-pylance"` (which in-turn will download the language server)
- Set workspace settings to use the extension's language server `"python.languageServer": "Pylance"`
=> Use Pylance as default language server (#723)

repository-containers/github.com/terraform-providers/terraform-provider-azurerm/.devcontainer/Dockerfile
Update to go version 1.16, fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/11048
=> Update go version in the terraform azure provider

containers/azure-ansible/.devcontainer/library-scripts/docker-debian.sh, containers/azure-terraform/.devcontainer/library-scripts/docker-debian.sh, containers/codespaces-linux-stretch/.devcontainer/library-scripts/docker-debian.sh, containers/codespaces-linux/.devcontainer/library-scripts/docker-debian.sh, containers/codespaces-linux/.devcontainer/library-scripts/docker-in-docker-debian.sh, containers/dapr-dotnet/.devcontainer/library-scripts/docker-debian.sh, containers/dapr-javascript-node/.devcontainer/library-scripts/docker-debian.sh, containers/docker-from-docker-compose/.devcontainer/library-scripts/docker-debian.sh, containers/docker-from-docker/.devcontainer/library-scripts/docker-debian.sh, containers/docker-in-docker/.devcontainer/library-scripts/docker-in-docker-debian.sh, containers/kubernetes-helm/.devcontainer/library-scripts/docker-debian.sh, script-library/docker-debian.sh, script-library/docker-in-docker-debian.sh
`docker-ce-cli` already contains buildx but in microsoft repos it is in a separate package.
I have no idea where most of these scripts are being used but the same code seems to copied in a lot of places and didn't want to leave them out of sync.
@cpuguy83
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> install buildx when installing moby from microsoft repo

containers/codespaces-linux/.devcontainer/library-scripts/ruby-debian.sh, containers/ruby/.devcontainer/library-scripts/ruby-debian.sh, script-library/ruby-debian.sh
rbenv fails to install rubies without libreadline-dev.
=> [codespaces] Add libreadline-dev for building ruby

script-library/common-debian.sh
Set `PROMPT_DIRTRIM` for the default codespaces prompt for a more tidy look.
See the `...` below.
closes #808
=> codespaces - utilize PROMPT_DIRTRIM to clean up PROMPT

containers/php-mariadb/.devcontainer/Dockerfile
The PHP+MariaDB image does not install any PHP extension.
This PR adds the pdo_mysql extension since the user will likely want to connect to the database in the app.
=> php-mariadb: install pdo_mysql driver

containers/javascript-node/.devcontainer/Dockerfile, containers/javascript-node/.devcontainer/base.Dockerfile, containers/javascript-node/.devcontainer/devcontainer.json, containers/javascript-node/README.md, containers/javascript-node/definition-manifest.json, containers/typescript-node/.devcontainer/Dockerfile, containers/typescript-node/.devcontainer/base.Dockerfile, containers/typescript-node/.devcontainer/devcontainer.json, containers/typescript-node/README.md, containers/typescript-node/definition-manifest.json
This PR adds Node.js 16 which was recently released. However, we're currently blocked by the upstream image due to https://github.com/nodejs/docker-node/issues/1466, https://github.com/docker-library/official-images/pull/10030. But we can expect a new `node:16` image soon, and we can merge at that point.  I also pointed out the history files we now have in the READMEs and made a couple corrections.
/cc: @joshspicer @2percentsilk for an example of this kind of update.
=> Add Node 16

script-library/docker-in-docker-debian.sh, script-library/terraform-debian.sh
Thanks to great suggestion in #843. This avoids API limits. Unfortunately, this doesn't work for the git/git build script given there are only tags.
=> Use release URL instead of GitHub API for two library scripts 

containers/alpine/definition-manifest.json, containers/codespaces-linux-stretch/definition-manifest.json, containers/codespaces-linux/definition-manifest.json, containers/cpp/definition-manifest.json, containers/debian/definition-manifest.json, containers/dotnet/definition-manifest.json, containers/go/definition-manifest.json, containers/java-8/definition-manifest.json, containers/java/definition-manifest.json, containers/javascript-node/definition-manifest.json, containers/php/definition-manifest.json, containers/python-3-anaconda/definition-manifest.json, containers/python-3-miniconda/definition-manifest.json, containers/python-3/definition-manifest.json, containers/ruby/definition-manifest.json, containers/rust/definition-manifest.json, containers/typescript-node/definition-manifest.json, containers/ubuntu/definition-manifest.json
/cc @2percentsilk @joshspicer  @alexr00 @chrmarti @jkeech 
PR'ing this for awareness. Given we're in endgame week for VS Code, we should get a monthly update of all images to pick up patches.  This will also land the `devcontainer-info` command into each image along with labels from #828.
I'll cut a 0.175.0 release here to get the changes out.
=> Bump image versions for upcoming VS Code release

script-library/common-debian.sh
This PR adds a systemctl stub when `systemd` is not in use. This helps avoid confusion in instructions by routing developers to use the `service` command instead which works with `/etc/init.d` services.
=> systemctl stub

script-library/common-alpine.sh, script-library/common-debian.sh, script-library/common-redhat.sh
Related to #848. This updates the first run notice check to verify that the TERM_PROGRAM is set for scenarios when the `userEnvProbe` setting will cause bashrc to be sourced.
//cc: @chrmarti @bamurtaugh @2percentsilk @joshspicer
=> Check for TERM_PROGRAM variable for notice

script-library/common-debian.sh
The dart container fails to load because it fails to install manpages-posix and manpages-posix-dev. I checked and found this:
```
> cat /etc/apt-sources-list
deb http://httpredir.debian.org/debian buster main
deb http://httpredir.debian.org/debian buster-updates main
deb http://security.debian.org buster/updates main
```
The sed rewriting was only looking for deb.debian.org, and this change makes it also look for httpredir.debian.org.
=> Fix apt sources rewrite to handle httpredir.

containers/jekyll/.devcontainer/post-create.sh
In setting up a Codespace for a site of mine, `post-create.sh` failed. This was because my Gemfile.lock contained these lines:
BUNDLED WITH
1.17.3
These lines indicate that the Bundler version that should be used with my Gemfile is 1.17.3. 
However, when the Dockerfile is run and the image created, it will get the latest bundler version of, today, 2.x.
When Bundler 2.x attempts to install gems for a Gemfile.lock BUNDLED WITH 1.x, it will fail.
In order to fix this, update the post-create.sh file to read the BUNDLED WITH declaration and install that version of Bundler.
When invoking the `bundle` command, it will read the Gemfile.lock and load the correct version automatically once it's installed.
=> jekyll: update post-create.sh to install the Bundler version that was used to generate the Gemfile.lock

containers/jupyter-datascience-notebooks/.devcontainer/devcontainer.json
This PR is a tweak to the Jupyter Data Science Notebooks definition that ensures Juypter server starts automatically and is forwaded locally so people can access it directly as neeeded w/o doing anything from the command line.
Look good @nathancarter ?
//cc @dynamicwebpaige
=> Ensure Jupyter server starts, is forwarded

containers/codespaces-linux/.devcontainer/library-scripts/common-debian.sh, script-library/common-debian.sh
fixes: https://github.com/microsoft/vscode-dev-containers/issues/878
Pulls from the skeleton file in our `common-debian.sh` if the .bashrc and .profile do not exist (or are empty).
=> Restore bashrc and profile from skeleton file if file doesn't exist

containers/java/.devcontainer/base.Dockerfile, containers/java/definition-manifest.json
Resolves issue where the SDKMAN installed version of Java does not show up in the path if you are using a non-interactive terminal.  Related to #895.
=> Fix SDKMAN java version path issue

containers/codespaces-linux/.devcontainer/base.Dockerfile, containers/java/.devcontainer/base.Dockerfile
As discussed in #895, the PATH in both the java and codespaces-linux definition is supposed to include the location that SDKMAN would install maven or gradle... specifically `${SDKMAN_DIR}/candidates/maven/current/bin` and `${SDKMAN_DIR}/candidates/gradle/current/bin`
Unfortunatley the `candidates` part was missing. As a result, the image works if you use it interactively since SDKMAN injects it, but any non-interactive interactions will not find either tool.
This fixes the paths.
=> Fix issue with path for SDKMAN installed tools

script-library/node-debian.sh
NVM version can now be set via the NVM_VERSION variable in the script, so future updates should be easier
=> Update NVM version

script-library/sshd-debian.sh
This simplifies the code to restore secrets in Codespaces when using SSH to connect to a dev container.
Verified working using https://github.dev/Chuxel/ssh-env-fix-test
//cc: @chrmarti @jkeech as FYI
=> Use new .env file for secret restoration in SSH script

script-library/common-alpine.sh, script-library/common-debian.sh, script-library/common-redhat.sh
fixes https://github.com/github/codespaces/issues/3012
More closely matches [how ohmyzsh displays git ref information on a detached HEAD](https://github.com/ohmyzsh/ohmyzsh/blob/d646884add277d134235a9b18ab755388d6e0d8d/lib/git.zsh#L20-L23).  
The behavior in a standard common-debian bash shell, when browsing a detached HEAD, changes from: 
to
=> Change bash git ref prompt to more closely match zsh

repository-containers/github.com/python/cpython/.devcontainer/devcontainer.json
This will create and install a standard binary instead of a shared library (better for most use cases)
=> Adjust the post build script

containers/rust/.devcontainer/devcontainer.json
- use [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) for better linting and auto-complete 
- add [crates](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates) extension for better experience when editing `Cargo.toml`
- use [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) for an even better experience when editing `Cargo.toml`
=> Update rust devcontainer.json

script-library/kubectl-helm-debian.sh
This PR adds bash and zsh completion for kubectl which provides a better developer experience and prevents inherited containers from having to implement.
=> add bash and zsh completion for kubectl

containers/typescript-node/README.md
the `vscode` user is not created - this image uses the `node` user
=> :pencil: non-root user is wrong

containers/vue/.devcontainer/Dockerfile, containers/vue/.devcontainer/devcontainer.json
Since the recommended node version choices for [`javascript-node`](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/javascript-node/.devcontainer/base.Dockerfile) has been changed, I updated the template for Vue, which relies on `javascript-node`.
- Remove choice for node version 10.
- Add choice for node version 16.
- Change default node version choice from 14 to 16.
=> Update vue .devcontainer template

containers/codespaces-linux/.devcontainer/base.Dockerfile, containers/codespaces-linux/definition-manifest.json
The image `exp-20210721.2` was creating `oryx-build-commands.txt` file in the user directory which we want to avoid. Hence, the old image was not pushed to prod. This image is built upon  `exp-20210721.2` with a fix to the bug.
https://github.com/microsoft/Oryx/releases/tag/20210728.1
=> Codespaces - Oryx version bump to 20210728.1

containers/alpine/definition-manifest.json, containers/cpp/definition-manifest.json, containers/debian/definition-manifest.json, containers/dotnet/definition-manifest.json, containers/go/definition-manifest.json, containers/java-8/definition-manifest.json, containers/java/definition-manifest.json, containers/javascript-node/definition-manifest.json, containers/jekyll/definition-manifest.json, containers/php/definition-manifest.json, containers/python-3-anaconda/definition-manifest.json, containers/python-3-miniconda/definition-manifest.json, containers/python-3/definition-manifest.json, containers/ruby/definition-manifest.json, containers/rust/definition-manifest.json, containers/typescript-node/definition-manifest.json, containers/ubuntu/definition-manifest.json, repository-containers/images/github.com/microsoft/vscode/definition-manifest.json
This PR is part of our roughly monthly release cycle for picking up library updates as a part of the VS Code release cycle. 
The "unversial" image is covered under #974
//cc @alexr00 with @chrmarti being OOF
=> Increment breakfix number for images for 1.59 release

containers/r/.devcontainer/devcontainer.json
Removed "R Language Server Pack" from `devcontainer.json` extensions. Enabling the extension in newer versions of VS Code results in the following error:
```
The R language server extension has been integrated into vscode-R. You need to disable or uninstall REditorSupport.r-lsp and reload window to use the new version.The R language server extension has been integrated into vscode-R. You need to disable or uninstall REditorSupport.r-lsp and reload window to use the new version.
```
=> remove R-LSP extension

containers/r/.devcontainer/Dockerfile, containers/r/.devcontainer/devcontainer.json
- Remove `reditorsupport.r-lsp` as its functionality has been merged into `ikuyadeu.r`. (https://github.com/REditorSupport/vscode-R/pull/695)
- `r.sessionWatcher` is now true by default, so remove it from settings. (https://github.com/REditorSupport/vscode-R/pull/670)
- Remove the `--repos` option from the `install2.r` command, which install the R packages in the container, as it is unnecessary. (Related to the base image improvement: https://github.com/rocker-org/rocker-versioned2/pull/195)
- Install the `httpgd` package for better plot viewer. (https://github.com/REditorSupport/vscode-R/pull/620)
- Edit the Rprofile to enable self-managed R sessions and use `httpgd` by default in VSCode.
- Add a setting to make it easier to use `radian` in the integrated terminal.
cc @kmehant @Ikuyadeu …
=> Update the R definition

script-library/go-debian.sh
dlv-dap is a delve built from the head.
since go1.16 (latest), 
* GO111MODULE=on is the default.
* `go install` is the recommended way of installing tools and from go1.17 (to be released soon), `go get` will print out
deprecation warning message and encourage users to use `go install`.
(If you want to keep this script usable for go1.15, I can revert this part back).
Fixes #984
=> install dlv-dap and use `go install` to install go tools

containers/go/.devcontainer/Dockerfile, containers/go/.devcontainer/base.Dockerfile, containers/go/.devcontainer/devcontainer.json, containers/go/.devcontainer/library-scripts/go-debian.sh, containers/go/README.md, containers/go/definition-manifest.json, script-library/go-debian.sh
closes https://github.com/microsoft/vscode-dev-containers/issues/1000
Updates our versions of `go` to track latest supported
=> update golang to in-support versions (1.16 and 1.17)

build/assets/release-notes-variant-part.md, build/src/image-info.js, build/src/push.js, build/src/utils/async.js, build/src/utils/config.js
Implements https://github.com/microsoft/vscode-dev-containers/issues/914. 
This PR does not update config to start building linux/arm64, but rather sets up the build system to do so. See https://github.com/microsoft/vscode-dev-containers/issues/558#issuecomment-905117722 for issues preventing switch, current plan of action.
=> Update build system to use buildx, support multi-arch builds

script-library/docker-in-docker-debian.sh
I found the indentation of `usermod -aG docker ${USERNAME}` to be incorrect. 
Signed-off-by: Aaqa Ishtyaq <aaqaishtyaq@gmail.com>
=> fix: update indentation in Dind-debian script

.github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, containers/debian/README.md, containers/debian/definition-manifest.json, containers/ubuntu/.devcontainer/Dockerfile, containers/ubuntu/.devcontainer/base.Dockerfile, containers/ubuntu/.devcontainer/devcontainer.json, containers/ubuntu/README.md, containers/ubuntu/definition-manifest.json
As described in https://github.com/microsoft/vscode-dev-containers/issues/558#issuecomment-905117722, the situation for Docker on M1 macs is not ideal since both `debian:buster` nor `ubuntu:focal` experience segmentation faults due to an issue in `libss1.1`. It seems unlikely that `buster` will be patched now that `bullseye` is out (and buster therefore gets security fixes only). Unclear about Ubuntu 20.04/Focal.
1. Adds arm64 builds for Debian `bullseye` and `stretch`, but leaves `buster` as x86 only.
2. Adds arm64 builds for Ubuntu `bionic`, but leaves `focal` as x86 only.
3. Breaks our typical policy of focusing on LTS releases considering the situation and adds an Ubuntu 21.04 / `hirsute` variant with arm64 support.
//cc: @joshspicer @2percentsilk @bamurtaugh …
=> Build arm64 image variations for the debian and ubuntu definitions for M1 macs

containers/javascript-node/.devcontainer/Dockerfile, containers/javascript-node/.devcontainer/base.Dockerfile, containers/javascript-node/.devcontainer/devcontainer.json, containers/javascript-node/README.md, containers/javascript-node/definition-manifest.json, containers/typescript-node/.devcontainer/Dockerfile, containers/typescript-node/.devcontainer/base.Dockerfile, containers/typescript-node/.devcontainer/devcontainer.json, containers/typescript-node/README.md, containers/typescript-node/definition-manifest.json
This PR updates the javascript and typescript definitions to to include arm64 pre-built images. As described in #558, there are challenges with Debian 10/buster. Unfortunately, the default `node` image in DockerHub is still on `buster`.
To provide the needed flexibility, this PR:
1. Introduces `-bullseye` flavors of each Node version and makes this the default (e.g. `16` == `16-bullseye`)
2. Keeps the existing `-buster` favors of the image for those that prefer to use them, or hit an unexpected issue.
3. Updates the choice of versions to include all variations so developers can pick which one they want to pin to.
4. Drops the old `-stretch` variations for 14/12 that we were not advertising anyway.
5. Builds arm64 images for the `-bullseye` variants.
=> Add Javascript / Typescript arm64 images

.github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, containers/javascript-node/README.md, containers/python-3/.devcontainer/Dockerfile, containers/python-3/.devcontainer/base.Dockerfile, containers/python-3/.devcontainer/devcontainer.json, containers/python-3/README.md, containers/python-3/definition-manifest.json, containers/typescript-node/.devcontainer/devcontainer.json, containers/typescript-node/README.md, repository-containers/images/github.com/microsoft/vscode/definition-manifest.json
3. Defaults to `bullseye` since this is what the upstream `python` image has done.
4. Makes a few README tweaks to the js/ts definition for consistency.
//cc: @joshspicer @2percentsilk @bamurtaugh @chrmarti
=> Python arm64 support, buster variants for back compat

.github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, containers/php/.devcontainer/Dockerfile, containers/php/.devcontainer/base.Dockerfile, containers/php/.devcontainer/devcontainer.json, containers/php/README.md, containers/php/definition-manifest.json, containers/python-3/README.md, containers/python-3/definition-manifest.json
3. Defaults to `bullseye` since this is what the upstream `php` image has done.
4. Makes a few minor edits to the python definition `README.md` and `definition-manifest.json`.
This also adds `php:<PHP VESION>-apache-<OS>` tags because of the tagging scheme used in the `php` upstream …
=> PHP arm64 support, buster variants for back compat

.github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, containers/go/.devcontainer/Dockerfile, containers/go/.devcontainer/base.Dockerfile, containers/go/.devcontainer/devcontainer.json, containers/go/README.md, containers/go/definition-manifest.json
3. Defaults to `bullseye` since this is what the upstream `go` image has done.
//cc: @joshspicer @2percentsilk @bamurtaugh @chrmarti
=> Go arm64, buster variants for back compat

.github/workflows/push-and-package.yml, .github/workflows/push-dev.yml, build/config.json, containers/go/definition-manifest.json, containers/javascript-node/definition-manifest.json, containers/jekyll/.devcontainer/Dockerfile, containers/jekyll/.devcontainer/base.Dockerfile, containers/jekyll/.devcontainer/devcontainer.json, containers/jekyll/README.md, containers/jekyll/definition-manifest.json, containers/php/.devcontainer/Dockerfile, containers/php/README.md, containers/php/definition-manifest.json, containers/python-3/definition-manifest.json, containers/ruby/.devcontainer/Dockerfile, containers/ruby/.devcontainer/base.Dockerfile, containers/ruby/.devcontainer/devcontainer.json, containers/ruby/README.md, containers/ruby/definition-manifest.json, containers/typescript-node/definition-manifest.json
3. Defaults to `bullseye` since this is what the upstream `ruby` image has done.
It also fixes a couple of tags for other images for consistency.
//cc: @joshspicer @2percentsilk @bamurtaugh @chrmarti
=> Ruby, Jekyll arm64 images, buster variants for back compat

containers/java-8/.devcontainer/Dockerfile, containers/java-8/.devcontainer/base.Dockerfile, containers/java-8/.devcontainer/devcontainer.json, containers/java-8/README.md, containers/java-8/definition-manifest.json, containers/java/.devcontainer/Dockerfile, containers/java/.devcontainer/base.Dockerfile, containers/java/.devcontainer/devcontainer.json, containers/java/README.md, containers/java/definition-manifest.json, containers/php/.devcontainer/devcontainer.json
3. Keeps the default image tags (8, 11, 16) at `buster`
@testforstephen @akaroml - Debian `bullseye` is pretty recent, but works on arm64. Would it make sense to default to stick with `buster` as is done here?  Java should be fairly abstracted from OS version updates, but I didn't want …
=> Java arm64 images, buster variants for back compat

containers/cpp/.devcontainer/Dockerfile, containers/cpp/.devcontainer/base.Dockerfile, containers/cpp/.devcontainer/devcontainer.json, containers/cpp/README.md, containers/cpp/definition-manifest.json
1. Adds arm64 build for Debian `bullseye` , `stretch`,  `hirsute`m `bionic`
2. Leaves `buster`, `focal` variants that are x86 only
3. Set the default image to `bullseye`
//cc: @joshspicer @2percentsilk @bamurtaugh @chrmarti
=> C++ arm64 images

containers/python-3-anaconda/README.md, containers/python-3-anaconda/definition-manifest.json
As described in #558 (comment), the situation for Docker on M1 macs is not ideal since both debian:buster nor ubuntu:focal experience segmentation faults due to an issue in libss1.1. It seems unlikely that buster will be patched now that bullseye is out (and buster therefore gets security fixes only).
Now that the `anaconda` image has moved to `bullseye`, we can add an arm64 build for it.
=> Anaconda arm64 image

containers/sfdx-project/.devcontainer/Dockerfile
This updates the image tag to the new format as per this stack exchange answer and verified on [docker hub](https://hub.docker.com/r/salesforce/salesforcedx/tags?page=1&ordering=last_updated)
Stack Exchange: https://salesforce.stackexchange.com/questions/354209/manifest-for-salesforce-salesforcedxlatest-not-found-manifest-unknown-manifes
=> SFDX docker image tag change

script-library/docs/node.md, script-library/node-debian.sh
Currently it is possible to install node with the library script in such a way that needed commands for installing packages that use node-gyp are not present. This update defaults to checking for the presence of python, make, and gcc and installs them if they are missing.
=> Add option to install node-gyp dependencies in Node script

containers/r/.devcontainer/Dockerfile
Fix #1032
Since The `remotes::install_github` function uses the GitHub API, the build will fail at the end of the build in an environment where the GitHub API cannot be used.
Switch to an installation method that does not use the GitHub API to reduce the chance of a build failure.
After building this Dockerfile, I checked the number of `resources.core.remaining` with the following command, and confirmed that the GitHub API was not used.
```shell
curl \
-H "Accept: application/vnd.github.v3+json" \
https://api.github.com/rate_limit
```
https://docs.github.com/en/rest/reference/rate-limit
cc @kmehant
=> [R] install packages from GitHub without using GitHub API

script-library/docs/desktop-lite.md
* without setting VNC_RESOLUTION env variable, tigervnc will not start up
* copied values from repository-containers/images/github.com/microsoft/vscode/.devcontainer/base.Dockerfile
=> Provide VNC env variables in Dockerfile example

script-library/desktop-lite-debian.sh
* update WEBSOCKETIFY to version 0.10.0 to make it work with Python 3.9
* version 0.9.0 resulted in error "handler exception: 'array.array' object has no attribute 'fromstring'
* upstream fix: https://github.com/novnc/websockify/issues/473
=> Make VNC work with Python 3.9

containers/codespaces-linux/definition-manifest.json, containers/cpp/definition-manifest.json, containers/ubuntu/definition-manifest.json
The C++, base, and universal image versions need  to be bumped up to pick up the following recently reported OS security updates:
- Ubuntu Security Notification for curl Vulnerabilities (USN-5079-1)
- Ubuntu Security Notification for Git Vulnerability (USN-5076-1)
- Ubuntu Security Notification for GNU cpio Vulnerability (USN-5064-1)
=> Bump versions to pick up security fixes for 1.61 release

containers/hugo/.devcontainer/devcontainer.json
Add the template format option to prevent vscode from messing with the hugo template format in html files.
=> enable html format templating

containers/go/.devcontainer/Dockerfile
change user before run go get/install to avoid permission denied on `/go/pkg/mod/cache`.
```
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/go.uber.org: permission denied
go: writing go.mod cache: mkdir /go/pkg/mod/cache/download/go.uber.org: permission denied
```
Another way to fix the issue is run go commands as vscode
```dockerfile
RUN su vscode -c "go get -x <your-dependency-or-tool>"
```
=> fix: change user before run go get/install

containers/docker-in-docker/.devcontainer/library-scripts/docker-in-docker-debian.sh, script-library/docker-in-docker-debian.sh
This PR updates to the latest docker-in-docker script from the github.com/moby/moby (and docker/docker) repo. The script update improves things by moving all processes in the root cgroup to the init cgroup instead of just process 1. Not doing this causes errors in some cases - I stubmled on this when experimenting with using "lima" and "colima" to host Docker, but there are other cases that could happen whenever running directly on Linux as the host.
Given the nature of this update, it also switches from using lots of "sudo" statments when required to one sudo statement that is only fired of the main container user is non-root. It then also switches to /bin/sh to further improve performance given it is lower overhead.
=> Update to latest dind script, reduce overhead

containers/bazel/.devcontainer/Dockerfile, containers/bazel/.devcontainer/devcontainer.json, containers/bazel/README.md
Bazel has been historically painful to manage, Bazelisk is a more flexible official way to manage the version of the Bazel tool similar to nvm (Node Version Manager).
Fix #1153 
Similar context #947
=> Migrate Bazel to Bazelisk version manager

script-library/common-alpine.sh, script-library/common-debian.sh, script-library/common-redhat.sh, script-library/docs/common.md
This PR resolves https://github.com/microsoft/vscode-dev-containers/issues/986 by allowing users to disable the git stauts part of the default prompt.  
It is modeled after Oh My Zsh!'s use of git config to handle this same situation so you can vary the behavior by repo and you do not need to update global env vars to change it. This also allows it to survive a "rebuild" if set for a repository.
To update:
```
git config codespaces-theme.hide-status 1
```
Or globally (e.g. from dotfiles):
```
git config --global codespaces-theme.hide-status 1
```
This works with both the bash and ZSH prompts, though OMZ has its own setting that also works.
I also: 
1. Removed the old "Oh My Bash" stub which was removed 9 months ago since enough time has passed.
2. Handled scenarios where the non-root …
=> Allow disable git status, drop omb stub, handle gid in different group name

containers/cpp/.devcontainer/devcontainer.json
@esweet431 - I'm wondering if we should add CMake Tools to VS Code's default C++ dev container. The Dockerfile installs cmake. @bobbrow - Do you know if we do this for Codespaces?
=> Add cmake-tools to default C++ container?

containers/elixir-phoenix-postgres/.devcontainer/Dockerfile
The checksum verification is comparing the node-debian.sh to the
common-debian.sh checksum, which fails if the `COMMON_SCRIPT_SHA`
environment variable is set.
This PR fixes the issue, comparing the node-debian.sh checksum to
the `NODE_SCRIPT_SHA` environment variable.
=> Fix Node script checksum verification

script-library/rust-debian.sh
Recently encountered a failure adding the rust layer on an M1 Mac.
This was a fairly simple fix.
=> Use variable for architecture when installing rust.

containers/codespaces-linux/definition-manifest.json, containers/cpp/definition-manifest.json, containers/debian/definition-manifest.json, containers/dotnet/definition-manifest.json, containers/go/definition-manifest.json, containers/javascript-node/definition-manifest.json, containers/jekyll/definition-manifest.json, containers/python-3-anaconda/definition-manifest.json, containers/python-3-miniconda/definition-manifest.json, containers/python-3/definition-manifest.json, containers/ruby/definition-manifest.json, containers/rust/definition-manifest.json, containers/typescript-node/definition-manifest.json, containers/ubuntu/definition-manifest.json
Alpine and PHP were skipped due to #1181 and #1179.
=> Bump minor version to pick up latest OS, runtime updates for 1.63 release

containers/ubuntu/.devcontainer/base.Dockerfile
'hirsuite' should be 'hirsute'
=> fix: Ubuntu version name typo in Dockerfile

containers/r/.devcontainer/devcontainer.json
The extension has been changed to add a terminal profile `R Teminal` (https://github.com/REditorSupport/vscode-R/pull/851), so the profile `radian` defined in `devcontainer.json` is no longer needed.
=> [R] Remove aditional terminal profile

script-library/kubectl-helm-debian.sh
Allow user to replace `.oh-my-zsh` folder.
Useful when install `dotfiles` repo in `codespace`, it run `dotfiles` repo's install script with non-root user.
=> fix(script-library): kubectl zsh completion file permission

containers/java/.devcontainer/base.Dockerfile, containers/java/definition-manifest.json
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
Fixes #1050
Use debian as the base image, and install Microsoft OpenJDK 11/17 via tar.gz download url on the docker image.
=> Move to Microsoft OpenJDK

containers/java/.devcontainer/base.Dockerfile
The new Microsoft OpenJDK version of the Java image works great! However, one thing I noticed is the current openjdk:bullseye image we have been using has a different JAVA_HOME location.
This PR tweaks JAVA_HOME to match the current images in the event someone has added this exact path to their settings.json for the various Java VS Code extensions instead of the common `/docker_java_home` folder.
=> Symlink legacy JAVA_HOME location

script-library/kubectl-helm-debian.sh
My devcontainer was failing to install my dotfiles because of this since many days, and I spent several days to track this change to here. That was mainly because I didn't pin the revision of the script to use, so I was always using the latest.
The problem is that, this script creates the OMZ folder as root since https://github.com/microsoft/vscode-dev-containers/pull/1163, and forgets to change its ownership back to the original non-root user.
Also, this PR addresses some ShellCheck warnings.
=> Fix OMZ folder ownership after installing completions

script-library/kubectl-helm-debian.sh
I noticed this in one of my images: https://github.com/felipecrs/docker-images/runs/4541686579?check_suite_focus=true#step:7:4000
=> Fix kubectl script when USERNAME is not set

script-library/fish-debian.sh
- Support `debian:bullseye`
- Update the install comand for debian (see https://software.opensuse.org/download.html?project=shells%3Afish&package=fish)
cc @andreiborisov
=> Update the install fish script

script-library/docs/github-cli.md
This documentation says to use `"github": "latest"`. However, it doesn't appear that the GitHub CLI is installed when doing this. Using `"github-cli": "latest"` does install the GitHub CLI tool, though.
=> fix incorrect github-cli documentation

script-library/ruby-debian.sh
Resolves #1235, enables #1226 
Installing `ruby-debug-ide` will install the right version of the `debase` gem if missing and installing `debase` directly fails on Ruby 3.1.0 as of 1/7/2022, so omitting.
=> Remove explicit debase install for Ruby script

containers/swift/.devcontainer/Dockerfile, containers/swift/.devcontainer/devcontainer.json, containers/swift/README.md
Changing the setting and installed extension. To reflect the latest state of Swift development.
[introducing-swift-for-visual-studio-code](https://forums.swift.org/t/introducing-swift-for-visual-studio-code/54246)
=> Update dev container for swift

container-templates/docker-compose/.devcontainer/Dockerfile, container-templates/dockerfile/.devcontainer/Dockerfile, containers/cpp/.devcontainer/Dockerfile, containers/cpp/.devcontainer/base.Dockerfile, containers/cpp/README.md, containers/debian/.devcontainer/Dockerfile, containers/debian/.devcontainer/base.Dockerfile, containers/debian/.devcontainer/devcontainer.json, containers/debian/README.md
Debian 9 / Stretch is no longer getting security patches as it is EOL and it's community LTS support runs out in June of this year.  https://wiki.debian.org/LTS
We should not be recommending it to people at this point. We can keep pre-building the stretch image for existing use until June as long as there isn't a critical security issue that is "won't fix".
=> Do not recommend Debian 9/stretch

containers/hugo/.devcontainer/Dockerfile
Recently `javascript-node`, the base image of Hugo container, [supports arm64 architecture](https://github.com/microsoft/vscode-dev-containers/blob/04c2d3ff7950d3f71fd1716ac131497f21c3fea5/containers/javascript-node/README.md).
> x86-64, arm64/aarch64 for bullseye variants
That means you can use Hugo container with arm64 by specifying kind of `16-bullseye` as `NODE_VERSION` argument. However, since it downloads amd64 binary version of `hugo` executable for the moment, hugo does not work natively in arm64 container.
This pull request makes it possible to switch the downloadable binary version by checking container OS processor architecture using `umame`.
=> Add arm64 support to Hugo container

containers/codespaces-linux/.devcontainer/library-scripts/sshd-debian.sh, script-library/sshd-debian.sh
Closes [#4095](https://github.com/github/codespaces/issues/4095)
In order to support multi-line secrets, we now encode secrets and write to  `/workspaces/.codespaces/shared/.env-secrets` file. We encode to this file, and decode while exporting env variables.
The codespaces image is however referencing to old `.env` file which prompts errors while connecting via ssh. Hence, changing the reference.
=> Codespaces: Change reference from .env to .env-secrets

containers/go-postgres/.devcontainer/Dockerfile, containers/go-postgres/test-project/go.mod, containers/go-postgres/test-project/go.sum
#920, and follow-up to [PR 1239](https://github.com/microsoft/vscode-dev-containers/pull/1239)
---
This PR updates the [go-postgress](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/go-postgres) container:
- Removes the need to have `RUN go get ...` called in the _DockerFile_
- Adds _go.mod_ and _go.sum_ to the _test-project_ folder, to keep the CI _test.sh_ script, and _F5-debug_, working
---
> Use the check-list below to ensure your branch is ready for PR.  If the item is not applicable, leave it blank.
---
> If this introduces a breaking change, please describe the impact and migration path for existing applications below.
---
After the changes, verified that:
- `test-project/test.sh` runs as expected
- `F5-debug` works as expected
---
The _go.mod_ and _go.sum_ …
=> Remove "RUN go get" from DockerFile in Go-Postgres container

script-library/container-features/src/devcontainer-features.json, script-library/docs/desktop-lite.md, script-library/docs/docker-in-docker.md, script-library/docs/docker.md, script-library/docs/kubectl-helm.md
A few of features enable the "tini" init process to help clean up zombie processes. While this is generally a good idea, it will conflict with the use of alternate init systems if added to a base image.
This PR moves this to a doc recommendation instead.
=> Remove forced "--init" in features to not consume PID 1

script-library/docker-redhat.sh
If using alternative distro, such as Rocky Linux, VERSION_ID prints out as "8.5" (depending on current minor version), which won't work well for most enterprise-linux repositories that use only major release version "8".
Here I simply trim out everything that comes after the dot, resulting in VERSION_ID=8, or in this case, RHEL_COMPAT_VER
=> trim minor version from VERSION_ID

containers/azure-static-web-apps/.devcontainer/Dockerfile, containers/azure-static-web-apps/.devcontainer/devcontainer.json
This PR brings a few changes:
- It updates the base image to `mcr.microsoft.com/azure-functions/python:4-python3.9-core-tools`, updating Python/Core Tools versions and allowing support for M1 macs
- It changes the default Node.js version to 16 instead of LTS to avoid unwanted upgrades and mismatch with core tools version
- It adds a `CORE_TOOLS_VERSION` param to allow switching to a different core tools version that the default one, for example if you wish to use a Node 14 version
- It fixes the mismatch between the previous default Node version (16) and Core Tools (v3) installed in the previous image
Fixes #1306
=> [Static Web Apps] Fix Node.js and Core Tools version mismatch

containers/ruby-rails-postgres/.devcontainer/Dockerfile, containers/ruby-rails-postgres/.devcontainer/docker-compose.yml
There’s only [one minor branch left with official support under Ruby 2.x ](https://www.ruby-lang.org/en/downloads/)(2.7) and it will likely be slated for end of life fairly soon, so it feels odd to default to a version that is 2 release behind latest stable. 
Also unless I’m mistaken Codespaces don’t run on ARM64/Apple Silicon so I’m not sure why bullseye is the default as well.
=> Default to non-ARM64 stable Ruby 3.1 release

containers/r/.devcontainer/Dockerfile
Suggested by #1314.
For users who want to use vscode-jupyter, add a section as a comment to install the necessary packages.
=> [R] Add comments how to install vscode-jupyter dependencies

containers/r/.devcontainer/Dockerfile, containers/r/.devcontainer/devcontainer.json
Suggested by https://github.com/microsoft/vscode-dev-containers/pull/1314#issuecomment-1049423896.
1. Allows the base image to be changed from the VSCode UI.
We can choose an image with the tidyverse package installed, which is considered to be in high demand (`rocker/tidyverse`), or a huge image with a large number of R packages and jupyter installed (`rocker/binder`).
2. Since a user `rstudio` exists in `rocker/tidyverse` and `rocker/binder` as a user with UID 1000, change the user name from `vscode` to `rstudio` to match this.
3. Allow the build args to control the installation of jupyter.
4. For arm64 builds (only exist for `rocker/r-ver`), the R packages are source installation, so add the necessary dependency packages in that case (`libfontconfig1-dev` and `libcairo2-dev`).
cc …
=> [R] Support for R package pre-installed images and arm64 images

containers/azure-terraform/README.md, containers/chef-workstation/README.md, containers/haskell/README.md, containers/sfdx-project/README.md, devcontainer-collection.json, migrations/options.json, migrations/readme-metadata-to-json.py
Includes little python script to parse the READMEs and spit out JSON.  Entire `devcontainer-collection.json` is auto-generated by the script from the `/containers` folder, so we can make changes to the source READMEs directly while we stabilize.
cc/ @Chuxel @chrmarti 
context/
https://github.com/github/codespaces/issues/6384
https://github.com/github/codespaces/issues/6265
https://github.com/microsoft/vscode-remote-containers/pull/191
=> tool to convert README metadata to json.

.devcontainer/Dockerfile, .devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/fluxbox/menu, .devcontainer/install.sh, .devcontainer/postCreateCommand.sh
This adds the dev container we've typically been using to review PRs to this repository to make reviewing easier.  We initally excluded it because we were worried about confusing people as to where things are located.
So, I added a README explaining it a bit to that part.  I'll also enable Codespace prebuilds.
=> vscode-dev-containers dev container

containers/go-postgres/.devcontainer/Dockerfile, containers/go-postgres/.devcontainer/docker-compose.yml, containers/go-postgres/README.md, containers/go/.devcontainer/base.Dockerfile, containers/go/.devcontainer/devcontainer.json, containers/go/README.md, containers/go/definition-manifest.json, script-library/container-features/src/devcontainer-features.json
Go 1.18 was just released. Once the upstream official Go 1.18 image is published, we can publish an updated image and drop 1.16 since its EOL.
=> Add Go 1.18 images, drop 1.16

containers/dotnet/.devcontainer/devcontainer.json, containers/java-8/definition-manifest.json, containers/java/definition-manifest.json, containers/jekyll/definition-manifest.json, containers/php/definition-manifest.json, containers/python-3-anaconda/definition-manifest.json, containers/python-3/definition-manifest.json, containers/ruby/definition-manifest.json, containers/rust/definition-manifest.json
Bump images that have not been updated recently to pick up latest updates.  Default rust to bullseye given the increase of Apple Silicon macOS devices.  C++/Ubuntu will be updated by #1399 and JS/TS will be updated by #1398 so they were omitted.  Go was just recently updated.
=> Bump for patching, default to bullseye

script-library/fish-debian.sh
All links on `git.io` will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
Replace `git.io` links with their actual URL.
=> replace `git.io` links with their actual URLs

script-library/github-debian.sh
closes https://github.com/microsoft/vscode-dev-containers/issues/1420
=> use `stable` instead of distro version for `github-debian.sh`

containers/ruby/.devcontainer/Dockerfile, containers/ruby/.devcontainer/base.Dockerfile, containers/ruby/.devcontainer/devcontainer.json, containers/ruby/README.md, containers/ruby/definition-manifest.json
Based on https://github.com/microsoft/vscode-dev-containers/issues/532 and https://www.ruby-lang.org/en/downloads/branches/, Ruby 2.6 has reached EOL.
Removing 2.6 from our files (covering files that were updated in a previous Ruby change in [this PR](https://github.com/microsoft/vscode-dev-containers/pull/851/files)).
=> Drop Ruby 2.6 EOL

containers/alpine/.devcontainer/Dockerfile, containers/alpine/.devcontainer/base.Dockerfile, containers/alpine/.devcontainer/devcontainer.json, containers/alpine/README.md, containers/alpine/definition-manifest.json
Based on https://github.com/microsoft/vscode-dev-containers/issues/532 and https://alpinelinux.org/releases/, it appears Alpine 3.12 has reached EOL. 
Updating our files to reflect this (following https://github.com/microsoft/vscode-dev-containers/pull/1181/files as an example).
=> Drop Alpine EOL 3.12

containers/codespaces-linux/.devcontainer/base.Dockerfile
Justification from @mylesborins
> Hey All, I noticed a weirdness with how npm is setup in codespaces, specifically that there is a a ~/.npmrc with the contents
prefix=/home/codespace/.npm-global
While this is good for making things a bit more “consistent” across versions of node / npm it does result in making it significantly more complicated to update npm independent of Node.js when installed via nvm since npm i -g npm installs into that prefix rather then the ~/.nvm folder, so the nvm installed version always will trump the customer installed npm version due to the order in $PATH
=> remove setting npm global location

containers/dotnet-fsharp/.devcontainer/Dockerfile, containers/dotnet-mssql/.devcontainer/Dockerfile, containers/dotnet-mssql/.devcontainer/docker-compose.yml, containers/dotnet-mssql/README.md, containers/dotnet-postgres/.devcontainer/Dockerfile, containers/dotnet-postgres/.devcontainer/docker-compose.yml, containers/dotnet/.devcontainer/Dockerfile, containers/dotnet/.devcontainer/base.Dockerfile, containers/dotnet/.devcontainer/devcontainer.json, containers/dotnet/README.md, containers/dotnet/definition-manifest.json
Update dotnet definitions as .NET 5.0 is EOL. Context: https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/
Made a few other updates since Node.js 10 and 12 are also EOL.
=> Update .NET 5.0 EOL

containers/azure-functions-java-11/.devcontainer/devcontainer.json, containers/azure-functions-java-8/.devcontainer/devcontainer.json, containers/clojure/.devcontainer/devcontainer.json, containers/java-8/.devcontainer/Dockerfile, containers/java-8/.devcontainer/base.Dockerfile, containers/java-8/.devcontainer/devcontainer.json, containers/java-8/.devcontainer/library-scripts/gradle-debian.sh, containers/java-8/.devcontainer/library-scripts/java-debian.sh, containers/java-8/.devcontainer/library-scripts/maven-debian.sh, containers/java-8/.devcontainer/library-scripts/node-debian.sh, containers/java-8/README.md, containers/java-8/definition-manifest.json, containers/java-postgres/.devcontainer/devcontainer.json, containers/java/.devcontainer/devcontainer.json, devcontainer-collection.json, script-library/container-features/src/devcontainer-features.json
Fixes #1444
- Remove "java.home" setting from devcontainer.json since it's deprecated in the latest Java extension.
- Remove JDK 11 from Java 8 container, since VS Code Java extension has embedded a JRE 17 in extension itself, no requirement for JDK 11 any more.
=> Update Java settings and JDK requirement in Java containers

containers/rust-postgres/.devcontainer/devcontainer.json, containers/rust-postgres/test-project/test.sh, containers/rust/.devcontainer/devcontainer.json, devcontainer-collection.json, script-library/container-features/src/devcontainer-features.json
The `matklad.rust-analyzer` extension has been replaced in favor of `rust-lang.rust-analyzer`. Since the old extension no longer exists, I've updated the referenced extension in the dev container configurations.
=> Rust: Target Correct Rust Analyzer Extension

containers/codespaces-linux/.devcontainer/library-scripts/jupyterlab-debian.sh, script-library/jupyterlab-debian.sh
Fixes a minor bug in the Jupyter install script by adding a setting for Jupyter Notebook. JupyterLab understands the `ServerApp.allow_origin` setting, but Jupyter Notebook needs `NotebookApp.allow_origin`.
Closes https://github.com/github/codespaces/issues/8194
=> Fix NotebookApp bug in Jupyter install script

script-library/git-lfs-debian.sh, script-library/test/regression/run-scripts.sh
closes #1473, which reported a change in the underlying file structure of the release artifacts. This manifested on "jammy", since git-lfs is not published in the jammy apt repo yet.
=> fix git-lfs install from git source 

script-library/fish-debian.sh, script-library/test/regression/run-scripts.sh
Fixes https://github.com/microsoft/vscode-dev-containers/issues/1501
=> Fix Fish shell installation

script-library/docker-debian.sh
It's not working because it's not getting installed. :)
=> Fix docker compose command v2 when not using moby

containers/javascript-node-mongo/.devcontainer/Dockerfile
The mongo database tools were originally not available for Debian Bullseye when this definition was last edited.  That has since changed.
In addition, arm64 support is not available for mongodb-database-tools but mongodb-mongosh is available. So this ensures the shell is always installed.
=> Update mongo tools install for latest available, add bullseye

script-library/docker-in-docker-debian.sh
This PR resolves the fact that docker compose v2 is no longer automatically installed with the docker-ce package.
=> Port fix in #1522 to docker-in-docker

containers/alpine/.devcontainer/Dockerfile, containers/alpine/.devcontainer/base.Dockerfile, containers/alpine/.devcontainer/devcontainer.json, containers/alpine/README.md, containers/alpine/definition-manifest.json
Alpine 3.16 was released on 2022-05-23 and is currently at 3.16.1. The new version has some updated stable packages. In particular, I'm interested in the updated `fzf` package, which does not depend on `perl`.
UPDATE: I release now that I need to generate release notes in `alpine/history`. Is there a tool I should use to create `history/0.204.5.md`?
=> Add Alpine 3.16

script-library/rust-debian.sh
Currently feature(rust) in devcontainer definition fails
container build unless user specifies nightly rust.
Issue was introduced in commit 10bf6f70c4f467be58dee5df8a7ff19cc598e09f
https://github.com/microsoft/vscode-dev-containers/pull/1554
Lack of "nightly" in RUST_VERSION will result in nonzero return code
from grep. This in turn triggers -e option set for the whole script.
As a result build silently fails.
=> rust-debian.sh: fix set -e interaction with nightly rust detection

containers/alpine/history/_history-files-have-moved.md, containers/codespaces-linux/history/_history-files-have-moved.md, containers/cpp/history/_history-files-have-moved.md, containers/debian/history/_history-files-have-moved.md, containers/dotnet/history/_history-files-have-moved.md, containers/go/history/_history-files-have-moved.md, containers/java-8/history/_history-files-have-moved.md, containers/java/history/_history-files-have-moved.md, containers/javascript-node/history/_history-files-have-moved.md, containers/jekyll/history/_history-files-have-moved.md, containers/php/history/_history-files-have-moved.md, containers/python-3-anaconda/history/_history-files-have-moved.md, containers/python-3-miniconda/history/_history-files-have-moved.md, containers/python-3/history/_history-files-have-moved.md, containers/ruby/history/_history-files-have-moved.md, containers/rust/history/_history-files-have-moved.md, containers/typescript-node/history/_history-files-have-moved.md, containers/ubuntu/history/_history-files-have-moved.md
As part of https://github.com/devcontainers/images/pull/106
Adding notes to the `history` files. 
cc @Chuxel
=> Add notes for migrated history files

container-templates/docker-compose/.devcontainer/devcontainer.json
I was playing with different mount options for my workspace and found that `"workspaceFolder"` is not optional. The comment vaguely suggests that you can set this to something other than a volume mount, but that only confused me further.
=> Use stronger wording in docker-compose template

script-library/docker-in-docker-debian.sh
By default the docker-in-docker script passes an Azure specific IP address to dockerd that causes Docker not to use the devcontainer's resolv.conf settings. We would like to not override DNS within Docker in some situations.
This PR adds a new `AZURE_DNS_OVERRIDE` flag that will give us the ability to disable this Azure DNS setting.
=> Add docker-in-docker Azure DNS override flag

containers/jupyter-datascience-notebooks/.devcontainer/devcontainer.json
The Python extension will no longer ship with the Jupyter extension.
https://github.com/microsoft/vscode-python/issues/18073
https://github.com/microsoft/vscode-python/pull/20218
=> included Jupyter extension to ds template

containers/docker-from-docker/README.md
The name of the destination mount point for the socket container does not match with the documentation
🚨 We are not accepting PRs for new Definitions/Templates or Features in this repository. 🚨
If you are an owner of a community Definition/Template or Feature and would like to have it removed from this repository (e.g., because you are now self-publishing), please create a PR here and let us know. Otherwise, note that the majority of the contents of this repository been migrated to the https://github.com/devcontainers org.  
* For new Dev Container Features, see https://github.com/devcontainers/feature-template to get started and add your Feature into the index.
* For new Definitions/Templates, see https://github.com/devcontainers/template-starter To get started and add your Template into …
=> fixed name of socket in documentation

script-library/shared/settings.env
GPG hangs indefindely when accessing these HTTP urls, which prevents Docker build from completing. And fetching these keys over an unprotected channel probably enables MIM attacks.
🚨 We are not accepting PRs for new Definitions/Templates or Features in this repository. 🚨
If you are an owner of a community Definition/Template or Feature and would like to have it removed from this repository (e.g., because you are now self-publishing), please create a PR here and let us know. Otherwise, note that the majority of the contents of this repository been migrated to the https://github.com/devcontainers org.  
* For new Dev Container Features, see https://github.com/devcontainers/feature-template to get started and add your Feature into the index.
* For new Definitions/Templates, see …
=> Bugfix: Ensure all GPG key servers use SSL

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, README.md
With the upcoming archiving of this repo, update information in the readme and issue/PR templates.
I also created an announcement issue, pinned it in the repo, and referenced it in this PR: https://github.com/microsoft/vscode-dev-containers/issues/1762.
=> Upcoming archive: Update readme and issue template
