microsoft/vscode-dev-containers

- containers/azure-ansible/.devcontainer/Dockerfile
- containers/azure-ansible/.devcontainer/devcontainer.json
- containers/azure-ansible/.npmignore
- containers/azure-ansible/README.md
Added azure-ansible dev container
Hope it helps!
> Added azure-ansible dev container

- CONTRIBUTING.md
- README.md
Clarifications per https://github.com/microsoft/vscode-dev-containers/issues/45#issuecomment-493480926
> README and CONTRIBUTING clarifications

- containers/perl/.devcontainer/Dockerfile
- containers/perl/.devcontainer/devcontainer.json
- containers/perl/.npmignore
- containers/perl/.vscode/launch.json
- containers/perl/README.md
- containers/perl/test-project/sample.pl
Added `Perl` development container definition for developing Perl applications using `vs code remote`
> Added Perl devcontainer definition

- containers/python-3-postgres/.devcontainer/docker-compose.yml
A simple fix in docker-compose configuration file.
> Mention dependency of app service over db service

- containers/javascript-node-lts-mongo/.devcontainer/docker-compose.yml
Changed docker-compose configuration for restarting database container when killed.
> Updated docker-compose configuration

- containers/azure-blockchain/.devcontainer/Dockerfile
- containers/azure-blockchain/.devcontainer/devcontainer.json
- containers/azure-blockchain/.npmignore
- containers/azure-blockchain/README.md
Added azure-blockchain dev container
Hope it helps!
> Added azure-blockchain dev container

- containers/javascript-node-lts-postgres/.devcontainer/Dockerfile
- containers/javascript-node-lts-postgres/.devcontainer/devcontainer.json
- containers/javascript-node-lts-postgres/.devcontainer/docker-compose.yml
- containers/javascript-node-lts-postgres/.npmignore
- containers/javascript-node-lts-postgres/.vscode/launch.json
- containers/javascript-node-lts-postgres/README.md
- containers/javascript-node-lts-postgres/test-project/package.json
- containers/javascript-node-lts-postgres/test-project/server.js
> Adding development container defination for NodeJS + Postgres

- containers/debian-9-git/.devcontainer/devcontainer.json
There is already an `"extensions"` field at line 19.
> Remove redundant "extensions" field.

- containers/docker-in-docker-compose/README.md
The Dockerfile won't execute as written
> Fix missing newline escape

- containers/alpine-3.10-git/.devcontainer/Dockerfile
- containers/alpine-3.10-git/.devcontainer/devcontainer.json
- containers/alpine-3.10-git/README.md
- containers/alpine-3.10-git/test-project/test.sh
Holding off merging until https://github.com/microsoft/vscode-remote-release/issues/1026 is resolved.  
Worst case, will back down to Alpine 3.9 for now if the Node and/or Alpine folks can't get us an answer. 
//cc: @chrmarti FYI
> Alpine 3.10 container

- containers/dotnetcore-3.0-fsharp/.devcontainer/Dockerfile
- containers/dotnetcore-3.0-fsharp/.devcontainer/devcontainer.json
- containers/dotnetcore-3.0-fsharp/.npmignore
- containers/dotnetcore-3.0-fsharp/.vscode/launch.json
- containers/dotnetcore-3.0-fsharp/.vscode/settings.json
- containers/dotnetcore-3.0-fsharp/.vscode/tasks.json
- containers/dotnetcore-3.0-fsharp/README.md
- containers/dotnetcore-3.0-fsharp/test-project/Program.fs
- containers/dotnetcore-3.0-fsharp/test-project/app.fsproj
Hopefully I got all the bits and blubs right in the files
> Add dotnetcore-3.0-fsharp

- containers/azure-functions-java-8/.devcontainer/Dockerfile
- containers/java-11/.devcontainer/Dockerfile
- containers/java-12/.devcontainer/Dockerfile
- containers/java-8-tomcat-8.5/.devcontainer/Dockerfile
- containers/java-8/.devcontainer/Dockerfile
Fixes #170
/cc: @testforstephen @chrmarti
> Move to Maven 3.6.3, use archive URL

- containers/ruby-2-rails-5/README.md
Fixed typo: fodlers to folders
> Fixed typo: fodlers to folders

- containers/azure-functions-pwsh-6/.devcontainer/Dockerfile
- containers/azure-functions-pwsh-6/README.md
See comment here for an explanation:
https://github.com/microsoft/vscode-dev-containers/pull/153#issuecomment-571336851
cc @TylerLeonhardt @brettmillerb
> Fix PowerShell example to use .Net Core 2.1 (2.2 was wrong)

- containers/jekyll/.devcontainer/Dockerfile
- containers/jekyll/.devcontainer/devcontainer.json
- containers/jekyll/.vscode/tasks.json
- containers/jekyll/README.md
Added a Jekyll developer container
Hope it helps!
> Added Jekyll developer container

- containers/azure-functions-dotnetcore-3.1/.devcontainer/Dockerfile
- containers/azure-functions-dotnetcore-3.1/.devcontainer/devcontainer.json
- containers/azure-functions-dotnetcore-3.1/.npmignore
- containers/azure-functions-dotnetcore-3.1/README.md
> Adding Azure Functions .NET Core 3.1 devcontainer

- containers/dotnetcore-2.1/.devcontainer/Dockerfile
- containers/dotnetcore-3.0/.devcontainer/Dockerfile
- containers/dotnetcore-3.1-fsharp/.devcontainer/Dockerfile
- containers/dotnetcore-3.1-fsharp/.devcontainer/devcontainer.json
- containers/dotnetcore-3.1-fsharp/.npmignore
- containers/dotnetcore-3.1-fsharp/.vscode/launch.json
- containers/dotnetcore-3.1-fsharp/.vscode/settings.json
- containers/dotnetcore-3.1-fsharp/.vscode/tasks.json
- containers/dotnetcore-3.1-fsharp/README.md
- containers/dotnetcore-3.1-fsharp/test-project/Program.fs
- containers/dotnetcore-3.1-fsharp/test-project/app.fsproj
- containers/dotnetcore-3.1/.devcontainer/Dockerfile
- containers/dotnetcore-3.1/.devcontainer/devcontainer.json
- containers/dotnetcore-3.1/.npmignore
- containers/dotnetcore-3.1/.vscode/launch.json
- containers/dotnetcore-3.1/.vscode/settings.json
- containers/dotnetcore-3.1/.vscode/tasks.json
- containers/dotnetcore-3.1/README.md
- containers/dotnetcore-3.1/test-project/Program.cs
- containers/dotnetcore-3.1/test-project/aspnetapp.csproj
> Add .NET Core 3.1 definitions

- containers/go/.devcontainer/Dockerfile
Resolves #175 .
//cc: @stamblerre @chrmarti
> Install gopls, other tools as modules when supported

- containers/azure-functions-node-10/.devcontainer/Dockerfile
- containers/cpp/.devcontainer/Dockerfile
- containers/elm/.devcontainer/Dockerfile
- containers/markdown/.devcontainer/Dockerfile
- containers/markdown/.devcontainer/devcontainer.json
- azure-functions-node-10
- cpp
- elm
- markdown
> Use prebuilt images to improve perf for a few dev containers

- script-library/common-alpine.sh
- script-library/common-debian.sh
- script-library/common-redhat.sh
> Add openssh-client for git support

- .github/workflows/push-and-package.yml
- .github/workflows/push-dev.yml
- containers/vsonline-linux/.devcontainer/Dockerfile
- containers/vsonline-linux/.devcontainer/devcontainer.json
- containers/vsonline-linux/.devcontainer/symlinkDotNetCore.sh
- containers/vsonline-linux/.npmignore
- containers/vsonline-linux/README.md
- containers/vsonline-linux/definition-build.json
- containers/vsonline-linux/test-project/test.sh
Implements #155. 
Currently uses `default` as the image name and sets the version to `0.1.0`.
> Default Linux VS Online Dev Container

- containers/azure-functions-dotnetcore-2.1/.devcontainer/devcontainer.json
- containers/azure-functions-dotnetcore-3.1/.devcontainer/devcontainer.json
- containers/dapr-dotnetcore-3.1/.devcontainer/devcontainer.json
- containers/dotnetcore-2.1-fsharp/.devcontainer/devcontainer.json
- containers/dotnetcore-2.1/.devcontainer/devcontainer.json
- containers/dotnetcore-3.0-fsharp/.devcontainer/devcontainer.json
- containers/dotnetcore-3.0/.devcontainer/devcontainer.json
- containers/dotnetcore-3.1-fsharp/.devcontainer/devcontainer.json
- containers/dotnetcore-3.1/.devcontainer/devcontainer.json
Updated all references to the C# extension, which was recently
transferred to a new publisher ID.
> Update references to C# extension.

- containers/azure-machine-learning-python-3/.devcontainer/Dockerfile
- containers/azure-machine-learning-python-3/.devcontainer/devcontainer.json
- containers/python-3/.devcontainer/devcontainer.json
> Move Azure ML to Ubuntu base due to incompat with Debian

- containers/azure-machine-learning-python-3/.devcontainer/Dockerfile
- containers/python-3/.devcontainer/base.Dockerfile
- containers/python-3/.devcontainer/devcontainer.json
- containers/python-3/README.md
- script-library/README.md
> Ensure pylint has access to installed modules for Python 3, README updates

- containers/azure-functions-python-3/.devcontainer/Dockerfile
* Update to Python 3.8 using `mcr.microsoft.com/vscode/devcontainers/python:3.8`
* Update Azure Functions Core Tools to version 3
Resolves #270
> Update to Azure Functions Python to 3.8

- containers/vsonline-linux/.devcontainer/Dockerfile
> Update Dockerfile to install kubectl

- containers/javascript-node-12-postgres/.devcontainer/devcontainer.json
the official name is *PostgreSQL* ;-)
> fix(spelling): remove "s"

- containers/docker-in-docker-compose/.devcontainer/Dockerfile
- containers/docker-in-docker-compose/.devcontainer/devcontainer.json
- containers/docker-in-docker-compose/.devcontainer/docker-compose.yml
- containers/docker-in-docker-compose/README.md
- containers/docker-in-docker/README.md
> Update DIND Compose to match DIND, fix typos

- containers/vsonline-linux/.devcontainer/Dockerfile
- containers/vsonline-linux/.devcontainer/symlinkDotNetCore.sh
New version of oryx. Updated the symlink file for new dotnet versions.
> Update oryx version

- containers/docker-in-docker-compose/README.md
- containers/docker-in-docker/README.md
- containers/kubernetes-helm/.devcontainer/Dockerfile
- containers/kubernetes-helm/.devcontainer/devcontainer.json
- containers/kubernetes-helm/README.md
- script-library/docker-debian.sh
Fixes issues with non-root docker script that presented in Codespaces.
> DinD and Kubernetes-Helm Non-Root Bug Fix

- containers/docker-existing-docker-compose/.devcontainer/devcontainer.json
My `.editorconfig` removes trailing whitespace so I noticed this 😅
> Remove unnecessary space

- containers/codespaces-linux/.devcontainer/Dockerfile
https://github.com/MicrosoftDocs/vsonline/issues/472
> Allow use of dotnet tools in default Codespaces 

- containers/codespaces-linux/definition-manifest.json
Just finished testing the changes with @edgonmsft and everything looks good. Would you mind creating a release for this?
> Update codespaces image to 0.7.0

- repository-containers/github.com/terraform-providers/terraform-provider-azurerm/.devcontainer/Dockerfile
- repository-containers/github.com/terraform-providers/terraform-provider-azurerm/.devcontainer/devcontainer.json
This is an update version of the devcontainer I submitted to the AzureRM Terraform provider here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/6195
> Add devcontainer for terraform-providers-azurerm

- build/patch/2020-06-18/Dockerfile
- build/patch/2020-06-18/README.md
- build/patch/2020-06-18/patch.json
My first attempt at a security patch. Tested locally and with a private ACR.
> Patch for CVE-2020-13777

- containers/azure-terraform-0.11/.devcontainer/devcontainer.json
- containers/azure-terraform-0.12/.devcontainer/devcontainer.json
Changed the terraform plugin to use the one provided by hashicorp.
> changed terraform plugin to use the one provided by hashicorp.

- containers/azure-ansible/.devcontainer/devcontainer.json
Added default mount for Ansible Collections. Solving #368
> Added default mount for Ansible Collections

- containers/hugo/.devcontainer/Dockerfile
- containers/hugo/.devcontainer/devcontainer.json
- containers/hugo/.vscode/tasks.json
- containers/hugo/README.md
This creates a container configuration for Hugo static site generator
> Create container configuration for Hugo

- containers/codespaces-linux/.devcontainer/Dockerfile
- containers/codespaces-linux/.devcontainer/git-ed.sh
- containers/codespaces-linux/definition-manifest.json
https://github.com/microsoft/vscs-planning/issues/128
> Configure VSCode (or Insiders, if installed) as the default editor for git commits

- containers/deno/README.md
> Fix formatting

- containers/swift-5.2/.devcontainer/Dockerfile
- containers/swift-5.2/.devcontainer/devcontainer.json
- containers/swift-5.2/.npmignore
- containers/swift-5.2/README.md
- containers/swift-5.2/test-project/Package.swift
- containers/swift-5.2/test-project/Sources/main.swift
This change creates a container definition for swift language version 5.2.
Signed-off-by: Kevin Carter <kevin@cloudnull.com>
> Create a container definition for swift-5.2

- containers/bash/.devcontainer/Dockerfile
> Bash container -Adds 'add your own run statement' comment

- containers/hugo/README.md
#412 made the Hugo container compatible with Codespaces 🎉
> update hugo readme

- script-library/docker-redhat.sh
Added setup script (docker-redhat.sh) for docker-from-docker setups for redhat flavored distros
> Added script for docker-from-docker in redhat

- containers/codespaces-linux/.devcontainer/Dockerfile
Downloading and installing github CLI.
TODO: authentication in the next sprint.
> feat: updated code to download and install gh CLI.

- containers/codespaces-linux/.devcontainer/Dockerfile
Fixes https://github.com/MicrosoftDocs/vscodespaces/issues/685
> Alias code-insiders to code for Codespaces image

- containers/kubernetes-helm/.devcontainer/Dockerfile
- containers/kubernetes-helm/README.md
Signed-off-by: Aisuko <urakiny@gmail.com>
fix #438
> Fix the client.crt not found

- containers/jekyll/.devcontainer/Dockerfile
> Fixing #436

- containers/jekyll/.devcontainer/Dockerfile
> Added zlib1g-dev fixing #436

- containers/kubernetes-helm/.devcontainer/Dockerfile
- containers/kubernetes-helm/.devcontainer/copy-kube-config.sh
- containers/kubernetes-helm/README.md
The .bashrc script continues to get more complicated, so moving it to a separate file rather than inline. Other simplications as well as a part of https://github.com/microsoft/vscode-dev-containers/issues/409
> Move Kubernets - Helm config into a script, update layering

- containers/dart/.devcontainer/Dockerfile
- containers/dart/.devcontainer/devcontainer.json
- containers/dart/README.md
This is part of the work for #409
> Switch Dart to using common script, a VARIANT arg, improve layering

- containers/javascript-node/.devcontainer/Dockerfile
- containers/javascript-node/.devcontainer/base.Dockerfile
- script-library/node-debian.sh
Related to https://github.com/microsoft/vscode-dev-containers/issues/409
> Improve layering for javascript node definition

- containers/jekyll/.devcontainer/devcontainer.json
> Fixed postCreateCommand #447

- .github/workflows/push-dev.yml
- containers/dotnetcore-fsharp/.devcontainer/Dockerfile
- containers/dotnetcore-fsharp/.devcontainer/library-scripts/README.md
- containers/dotnetcore-fsharp/.devcontainer/library-scripts/common-debian.sh
- containers/dotnetcore-fsharp/.devcontainer/library-scripts/node-debian.sh
- containers/dotnetcore-fsharp/.npmignore
- containers/dotnetcore/.devcontainer/Dockerfile
- containers/dotnetcore/.devcontainer/devcontainer.json
- containers/dotnetcore/.devcontainer/library-scripts/README.md
- containers/dotnetcore/.devcontainer/library-scripts/common-debian.sh
- containers/dotnetcore/.devcontainer/library-scripts/node-debian.sh
- containers/dotnetcore/.npmignore
> Update dotnetcore to use library-scripts approach

- containers/docker-from-docker-compose/.devcontainer/Dockerfile
- containers/docker-from-docker-compose/.devcontainer/library-scripts/README.md
- containers/docker-from-docker-compose/.devcontainer/library-scripts/common-debian.sh
- containers/docker-from-docker-compose/.devcontainer/library-scripts/docker-debian.sh
- containers/docker-from-docker-compose/.npmignore
- containers/docker-from-docker-compose/README.md
- containers/docker-from-docker/.devcontainer/Dockerfile
- containers/docker-from-docker/.devcontainer/devcontainer.json
- containers/docker-from-docker/.devcontainer/library-scripts/README.md
- containers/docker-from-docker/.devcontainer/library-scripts/common-debian.sh
- containers/docker-from-docker/.devcontainer/library-scripts/docker-debian.sh
- containers/docker-from-docker/.npmignore
- containers/docker-from-docker/README.md
- containers/kubernetes-helm/.devcontainer/Dockerfile
- containers/kubernetes-helm/.devcontainer/library-scripts/README.md
- containers/kubernetes-helm/.devcontainer/library-scripts/common-debian.sh
- containers/kubernetes-helm/.devcontainer/library-scripts/docker-debian.sh
- containers/kubernetes-helm/.npmignore
- containers/kubernetes-helm/README.md
This PR is part of a repository cleanup to move towards using scripts for installing common dependencies and improve layering.
Reference: #409, #462
> Update docker-from-docker, kubernetes-helm to use library-scripts approach

- script-library/common-debian.sh
- script-library/docker-debian.sh
- script-library/node-debian.sh
- script-library/test/Dockerfile
> Avoid problems with duplicate multiple runs of same Debian library script

- containers/codespaces-linux/.devcontainer/Dockerfile
This PR simply adds the `less` utility to the Codespaces universal Linux image, since this is a common/valuable tool for many developers 👍
> Codespaces: Adding the "less" tool

- NOTICE.txt
- containers/php/.devcontainer/base.Dockerfile
- containers/php/definition-manifest.json
> Add composer to PHP definition

- containers/php-mariadb/.devcontainer/Dockerfile
- containers/php-mariadb/.devcontainer/devcontainer.json
- containers/php-mariadb/.devcontainer/docker-compose.yml
- containers/php-mariadb/README.md
- containers/php/.devcontainer/base.Dockerfile
- containers/php/.devcontainer/devcontainer.json
- containers/php/README.md
> Update PHP definition to use php:apache

- script-library/desktop-lite-debian.sh
- script-library/test/Dockerfile
- script-library/test/debian/.devcontainer.json
- script-library/test/run-scripts.sh
Instructions for use are in the comments in the top of the script. Subsequent script can add a larger desktop like Xfce or MATE.
> Add a light weight desktop script using Fluxbox

- containers/swift/.vscode/launch.json
Use the correct binary name in launch.json config file.
> Fix swift container launch.json

- script-library/common-debian.sh
- script-library/desktop-lite-debian.sh
- script-library/docker-debian.sh
- script-library/go-debian.sh
- script-library/gradle-debian.sh
- script-library/java-debian.sh
- script-library/maven-debian.sh
- script-library/node-debian.sh
- script-library/python-debian.sh
- script-library/ruby-debian.sh
- script-library/rust-debian.sh
- script-library/sshd-debian.sh
> Automatic user detection in library scripts

- containers/codespaces-linux/.devcontainer/base.Dockerfile
- containers/codespaces-linux/.devcontainer/library-scripts/git-from-src-debian.sh
- script-library/README.md
- script-library/docs/azcli.md
- script-library/docs/common.md
- script-library/docs/desktop-lite.md
- script-library/docs/git-from-src.md
- script-library/docs/git-lfs.md
- script-library/docs/github.md
- script-library/docs/go.md
- script-library/docs/gradle.md
- script-library/docs/java.md
- script-library/docs/kubctl-helm.md
- script-library/docs/maven.md
- script-library/docs/node.md
- script-library/docs/powershell.md
- script-library/docs/python.md
- script-library/docs/ruby.md
- script-library/docs/rust.md
- script-library/docs/sshd.md
- script-library/docs/terraform.md
- script-library/git-from-src-debian.sh
- script-library/go-debian.sh
- script-library/gradle-debian.sh
- script-library/node-debian.sh
- script-library/ruby-debian.sh
- script-library/terraform-debian.sh
Also adds "latest" mode into two scripts.
Fixes #563
> Script documentation and comment tweaks

- containers/azure-terraform/.devcontainer/Dockerfile
This PR resolves issue https://github.com/microsoft/vscode-dev-containers/issues/643
> Replace INSTALL_AZURE_CLI with INSTALL_NODE

- NOTICE.txt
- containers/codespaces-linux/.devcontainer/library-scripts/ruby-debian.sh
- containers/codespaces-linux/README.md
- containers/codespaces-linux/definition-manifest.json
- containers/ruby/.devcontainer/library-scripts/ruby-debian.sh
- containers/ruby/definition-manifest.json
- script-library/ruby-debian.sh
> Add rbenv to containers with ruby

- script-library/test/run-scripts.sh
Fixed microsoft/vscode-dev-containers#651
> Replace UPGRADE_PAGKES with UPGRADE_PACKAGES

- containers/azure-bicep/.devcontainer/Dockerfile
- containers/azure-bicep/.devcontainer/devcontainer.json
- containers/azure-bicep/.devcontainer/library-scripts/README.md
- containers/azure-bicep/.devcontainer/library-scripts/azcli-debian.sh
- containers/azure-bicep/.devcontainer/library-scripts/common-debian.sh
- containers/azure-bicep/.devcontainer/library-scripts/node-debian.sh
- containers/azure-bicep/.npmignore
- containers/azure-bicep/README.md
- containers/azure-bicep/test-project/main.bicep
Adding [Azure Bicep](https://github.com/Azure/bicep) dev container
> Adding Azure Bicep dev container

- containers/azure-bicep/.devcontainer/Dockerfile
- containers/azure-bicep/.devcontainer/devcontainer.json
@cmendible I noticed a couple things after I merged that we could probably tweak.  See what you think.
> Tweaks to Azure Bicep definitions

- containers/elixir-phoenix-postgres/.devcontainer/Dockerfile
- containers/elixir-phoenix-postgres/.devcontainer/devcontainer.json
- containers/elixir-phoenix-postgres/.devcontainer/docker-compose.yml
- containers/elixir-phoenix-postgres/.npmignore
- containers/elixir-phoenix-postgres/README.md
- containers/elixir-phoenix-postgres/test-project/test.sh
Hey, this PR is a revival of PR #432. I noticed that it had gone stale after September and would really love to have this Elixir + Phoenix + Node + Postgres dev container finished and merged.
I have addressed the comments in the PR (#432) and added one or two more nice to have in the configurations. If you have any more feedback just let me know. I love using Dev Containers (and Github Codespaces) and excited to contribute to something awesome.
> Elixir + Phoenix + Node.js + PostgreSQL Dev Container revival

- script-library/docker-in-docker-debian.sh
Fix the docker-in-docker script to work with non-root sudoers
> [docker-in-docker] sudoIf the find -delete statements

- containers/codespaces-linux/definition-manifest.json
- package.json
incorporates change in #741 to released image.
cc/ https://github.com/microsoft/vssaas-planning/issues/2499
> bump codespaces-linux to 1.1.3

- containers/javascript-node-azurite/.devcontainer/Dockerfile
- containers/javascript-node-azurite/.devcontainer/devcontainer.json
- containers/javascript-node-azurite/.devcontainer/docker-compose.yml
- containers/javascript-node-azurite/.npmignore
- containers/javascript-node-azurite/.vscode/launch.json
- containers/javascript-node-azurite/.vscode/settings.json
- containers/javascript-node-azurite/README.md
- containers/javascript-node-azurite/package-lock.json
- containers/javascript-node-azurite/test-project/.eslintrc.json
- containers/javascript-node-azurite/test-project/.gitignore
- containers/javascript-node-azurite/test-project/japaFile.js
- containers/javascript-node-azurite/test-project/package.json
- containers/javascript-node-azurite/test-project/test.sh
- containers/javascript-node-azurite/test-project/test/blob.spec.js
- containers/javascript-node-azurite/test-project/test/queue.spec.js
This is a new devcontainer that setup recommended extensions and ports for running Azurite locally in a devcontainer
It also contains two tests for `blob` and `queue`
> Add Azurite Node devcontainer

- containers/codespaces-linux/.devcontainer/base.Dockerfile
Updates the `codespaces-linux` base `Dockerfile` to install `python3-dev` per the conversation in [#2096](https://github.com/microsoft/vssaas-planning/issues/2096).
> Install python3-dev package for scenario

- script-library/docs/sshd.md
Added the following:
- Section on usage with a default kitchen sink image 
- Updates on how to forward a port
> Updates to the Readme

- script-library/README.md
- script-library/docs/fish.md
- script-library/fish-debian.sh
- script-library/test/run-scripts.sh
Resolves https://github.com/microsoft/vscode-dev-containers/issues/570
> Add fish shell install script to the script library

- containers/alpine/.devcontainer/library-scripts/common-alpine.sh
- containers/debian/.devcontainer/library-scripts/common-debian.sh
- script-library/common-alpine.sh
- script-library/common-debian.sh
- script-library/common-redhat.sh
This is a simple one-liner fix as described in #793. 
@matthewisabel is interested in an updated image for #795, so I got this one in quick while I was at it.
> Fix #793 (bash prompt shows tag)

- script-library/docs/rust.md
> :pencil: typo - go should be rust

- containers/alpine/.devcontainer/library-scripts/common-alpine.sh
- containers/codespaces-linux/.devcontainer/library-scripts/common-debian.sh
- containers/debian/.devcontainer/library-scripts/common-debian.sh
- script-library/common-alpine.sh
- script-library/common-debian.sh
- script-library/common-redhat.sh
Adds location that allows codespaces (or anything else) to inject dynamic messages as needed.
> Add alternate location for first run message

- containers/mit-scheme/.devcontainer/Dockerfile
- containers/mit-scheme/.devcontainer/devcontainer.json
- containers/mit-scheme/.devcontainer/library-scripts/README.md
- containers/mit-scheme/.devcontainer/library-scripts/common-debian.sh
- containers/mit-scheme/.devcontainer/mit-scheme-debian.sh
- containers/mit-scheme/.npmignore
- containers/mit-scheme/README.md
Signed-off-by: aisuko <urakiny@gmail.com>
fixes: #768
> Add new development container mit-scheme

- containers/docker-in-docker/.devcontainer/library-scripts/docker-in-docker-debian.sh
- script-library/docker-in-docker-debian.sh
> Fix docker-in-docker on Ubuntu bionic

- script-library/docker-debian.sh
- script-library/docker-redhat.sh
The GitHub API has rate limits.
> Prevent GitHub API call for install docker-compose

- containers/kubernetes-helm/README.md
> Dockerifle -> Dockerfile

- containers/codespaces-linux/.devcontainer/first-run-notice.txt
Adding configuration information to the welcome mat
> Add config step in welcome mat

- containers/python-3-pypy/.devcontainer/Dockerfile
- containers/python-3-pypy/.devcontainer/devcontainer.json
- containers/python-3-pypy/.devcontainer/library-scripts/README.md
- containers/python-3-pypy/.devcontainer/library-scripts/common-debian.sh
- containers/python-3-pypy/.npmignore
- containers/python-3-pypy/README.md
- containers/python-3-pypy/test-project/hello.py
Creates a python container using the [PyPy](https://www.pypy.org/) interpreter.
> Create a container that uses the PyPy interpreter

- containers/java/.devcontainer/Dockerfile
- containers/java/.devcontainer/base.Dockerfile
- containers/java/.devcontainer/devcontainer.json
- containers/java/README.md
- containers/java/definition-manifest.json
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
> Update to the latest Java JDK 16

- containers/dapr-dotnet/.devcontainer/devcontainer.json
- containers/dapr-dotnet/test-project/test.sh
- containers/dapr-javascript-node/.devcontainer/devcontainer.json
- containers/dapr-javascript-node/test-project/test.sh
This resolves #888 by running "uninstall" before "init" in postCreateCommand
Look good @philliphoff?
> Fix rebuild failure for dapr init

- .vscode/extensions.json
- CONTRIBUTING.md
Fixes #814 to recommend the EditorConfig extension when users are contributing to this repo
> Add editorconfig as a recommended extension

- containers/ruby-rails-postgres/.devcontainer/Dockerfile
- containers/ruby-rails-postgres/.devcontainer/devcontainer.json
- containers/ruby-rails-postgres/.devcontainer/docker-compose.yml
- containers/ruby-rails-postgres/README.md
As discussed in #703, these are some minor tweaks to keep things up to date with the latest Ruby definitions in this repo.
//cc @jarrodldavis as FYI
> Update ruby-rails-postgres with recent changes to Ruby definitions

- repository-containers/github.com/python/cpython/Dockerfile
- repository-containers/github.com/python/cpython/devcontainer.json
I have an outstanding question. does the container need to copy the source files from the workspace?
This docker file assumes the current path is the source of the cpython repo
CC @brettcannon
> Create a basic cpython container and devcontainer

- containers/alpine/.devcontainer/Dockerfile
- containers/alpine/.devcontainer/base.Dockerfile
- containers/alpine/.devcontainer/devcontainer.json
- containers/alpine/.devcontainer/library-scripts/common-alpine.sh
- containers/alpine/definition-manifest.json
- script-library/common-alpine.sh
> Add Alpine 3.14, deprcate 3.10

- script-library/common-alpine.sh
- script-library/common-debian.sh
- script-library/common-redhat.sh
> Set the default git editor if not already set

- containers/codespaces-linux/.devcontainer/base.Dockerfile
- containers/codespaces-linux/definition-manifest.json
Oryx tag - https://github.com/microsoft/Oryx/releases/tag/exp-20210721.2
It contains changes needed for [oryx build status should show the actual command oryx invokes](https://github.com/microsoft/vssaas-planning/issues/3931)
> Codespaces - Oryx version bump to exp-20210721.2

- containers/deno/.devcontainer/devcontainer.json
- containers/deno/README.md
👋  I am part of the @denoland core time and maintain denoland/vscode_deno.
There are a few things can be adjusted in the configuration to make a better out of the box experience with Deno when setting up a dev container.
> Improve the default experience for Deno containers

- containers/powershell/README.md
The description does not seem to match the sample script.
> minor fix powershell's README

- containers/javascript-node/definition-manifest.json
- containers/typescript-node/definition-manifest.json
Re-release node container image
> bump node container

- containers/codespaces-linux/.devcontainer/base.Dockerfile
- containers/codespaces-linux/.devcontainer/library-scripts/git-from-src-debian.sh
- script-library/git-from-src-debian.sh
Given our oryx upstream dependency, our npm version is lower than currently required.  Bumping it here by adding this line to the dockerfile
> bump npm to latest v6

- containers/codespaces-linux/.devcontainer/base.Dockerfile
- containers/codespaces-linux/definition-manifest.json
takes the latest upstream Oryx build 
https://github.com/microsoft/Oryx/releases/tag/20210805.1
> bump codespaces oryx upstream build

- containers/go/.devcontainer/Dockerfile
Updated nvm commands to install a specific version, or lts properly. Fixes #987
> Fixed bad conditional, fixed nvm install for lts

- containers/go/.devcontainer/Dockerfile
Reverts microsoft/vscode-dev-containers#988
> Revert "Fixed bad conditional, fixed nvm install for lts"

- script-library/azcli-debian.sh
While the Azure CLI team has now added pre-created binaries for the tool on Debian bullseye, arm64 is not currently pre-built. In these cases, the Azure CLI team recommends installing using pip. This is similar to what we end up having to do for docker-compose, so the code is largely the same. It uses pipx to avoid any library conflicts.
/cc: @joshspicer as FYI since this is a script we're looking at for "feature" support.
> Fall back on pip3 when installing Azure CLI on arm64

- containers/codespaces-linux/.devcontainer/base.Dockerfile
- containers/codespaces-linux/README.md
Pick up the latest oryx bits in the kitchen sink image.
> bump oryx base image to latest

- .github/workflows/smoke-dotnet.yaml
- containers/dotnet/.devcontainer/Dockerfile
- containers/dotnet/.devcontainer/base.Dockerfile
- containers/dotnet/.devcontainer/devcontainer.json
- containers/dotnet/definition-manifest.json
> Bump .NET default to 6.0 now that it is GA, trigger image update

- containers/php-mariadb/.devcontainer/Dockerfile
- containers/php-mariadb/.devcontainer/docker-compose.yml
- containers/php/.devcontainer/Dockerfile
- containers/php/.devcontainer/base.Dockerfile
- containers/php/.devcontainer/devcontainer.json
- containers/php/README.md
- containers/php/definition-manifest.json
Add PHP 8.1 now that it is out, drop 7.3 that is EOL
> Add PHP 8.1

- .github/workflows/container-features.yml
uses https://github.com/microsoft/publish-dev-container-features-action
> add action workflow for container features on release

- containers/codespaces-linux/.devcontainer/base.Dockerfile
- containers/codespaces-linux/definition-manifest.json
- containers/codespaces-linux/test-project/test.sh
closes https://github.com/microsoft/vscode-dev-containers/issues/1154
> [codespaces] bump oryx to 20211210.1

- CONTRIBUTING.md
```
- Dockefile
+ Dockerfile
```
> Update Dockerfile misspelling

- CONTRIBUTING.md
---
Added documentation that allows a maintainer or contributor to manually add Database support for any existing dev container definition. This will make it easier for contributors to add DB support for any language pair as needed.
---
> Use the check-list below to ensure your branch is ready for PR.  If the item is not applicable, leave it blank.
---
---
This Documentation change is primarily as a result of learnings from adding PostgreSQL DB support to Go and Java.
> Documentation Changes for Contributing.MD

- containers/codespaces-linux/.devcontainer/base.Dockerfile
fixes https://github.com/microsoft/vscode-dev-containers/issues/1245
> bump upstream oryx in codespaces-linux to 20220120.1

- containers/cpp-mariadb/.devcontainer/install-mariadb.sh
Fix #1275 
---
Unable to install `cpp-mariadb` containers since `mariadb_repo_setup` checksum is not the same as `mariadb_repo_setup.sha256`
---
1. Open Folder in Container: Select vscode-dev-containers/containers/cpp-mariadb folder
2. The install fails at:
```sh
> => extracting sha256:cb5b7ae361722f070eca53f35823ed21baa85d61d5d95cd5a95ab53d740cdd56          0.5s
=> => extracting sha256:4207b1a935e840209a17de034f70292ec8721674ee0162ce1b331ad85ae3c593          0.0s
=> => extracting sha256:f492ad3cc3917050c6d923862dd76edfe26394cfb1e737a4efe2f03076a5654d          6.2s
=> => extracting sha256:b877d8422c3385f21f5b70e1cccc870f30574f47b5b75529ac4a111563dc07a6          0.0s
=> => extracting sha256:a81ca82928ce670b7612c6b68accc214417467e1113954fd991ff2a49b753ec4         14.3s
=> [2/4] RUN apt-get …
```
> Remove checksum from install mariadb script

- README.md
- repository-containers/README.md
Based on https://github.com/microsoft/vscode-docs/pull/5198 and https://github.com/microsoft/vscode-remote-release/issues/6013
> Add repository containers docs link

- .devcontainer/README.md
Add the badge and link. Happy to discuss any wording or location suggestions!
cc @egamma @chrmarti
> Add links to open in container

- CONTRIBUTING.md
Change `a packages` to `a package`. I just dropped the extra 's'.
> Update extra 's' in CONTRIBUTING.md

- containers/r/.devcontainer/Dockerfile
- Add R 4.2 (released 2022-04-22)
- Fix the vscode-R's initialize command (only initialize on interactive vscode-R session)
> [R] Add R 4.2 and minor update

- build/src/utils/image-content-extractor.js
closes https://github.com/microsoft/vscode-dev-containers/issues/1435
> add safe dir to 'Update Version History' scripts

- repository-containers/images/github.com/microsoft/vscode/.devcontainer/base.Dockerfile
> Use node version 16

- containers/r/.devcontainer/devcontainer.json
> [R] Fix version

- containers/codespaces-linux/.devcontainer/library-scripts/kubectl-helm-debian.sh
- containers/kubernetes-helm-minikube/.devcontainer/library-scripts/kubectl-helm-debian.sh
- containers/kubernetes-helm/.devcontainer/library-scripts/kubectl-helm-debian.sh
- containers/kubernetes-helm/README.md
- devcontainer-collection.json
- script-library/container-features/src/devcontainer-features.json
- script-library/kubectl-helm-debian.sh
Spelling correction for "Minkube" across the repository. Apologies about the formatting changes, if that's an issue I can remove them and include just the spelling changes.
> Spelling correction: Minkube -> Minikube

- containers/kubernetes-helm-minikube/README.md
- containers/kubernetes-helm/README.md
- script-library/docs/kubectl-helm.md
Documents how to work around a Codespaces shortcoming when setting up ingress for Kubernetes. 
See https://twitter.com/Chuxel/status/1557151634593038339
//cc @jkeech @joshspicer
> Add info on using ingress in Codespaces

- containers/azure-functions-node/.devcontainer/Dockerfile
Necessary for local development.
> Update Functions/Node dockerfile to provide Azurite by default

- script-library/sshd-debian.sh
ref: https://github.com/devcontainers/features/issues/94
> backport: https://github.com/devcontainers/features/pull/96

- containers/alpine/definition-manifest.json
- containers/codespaces-linux/definition-manifest.json
- containers/cpp/definition-manifest.json
- containers/debian/definition-manifest.json
- containers/dotnet/definition-manifest.json
- containers/go/definition-manifest.json
- containers/java/definition-manifest.json
- containers/javascript-node/definition-manifest.json
- containers/jekyll/definition-manifest.json
- containers/php/definition-manifest.json
- containers/python-3-anaconda/definition-manifest.json
- containers/python-3-miniconda/definition-manifest.json
- containers/python-3/definition-manifest.json
- containers/ruby/definition-manifest.json
- containers/rust/definition-manifest.json
- containers/typescript-node/definition-manifest.json
- containers/ubuntu/definition-manifest.json
closes https://github.com/microsoft/vscode-dev-containers/issues/1590
> bump all images to get latest patches

- .github/workflows/release-templates.yml
Adds release workflow to publish community templates from https://github.com/microsoft/vscode-dev-containers/pull/1659 to OCI.
> Templates - add release workflow

- README.md
> Really visible typo

- containers/docker-from-docker-compose/README.md
- containers/docker-from-docker/README.md
Fixes a typo in the docker-from-docker docs.
> fix: Add -e for echo newlines to resolve properly

- script-library/shared/settings.env
Adds bookworm to `settings.env`
Fixes https://github.com/devcontainers/templates/actions/runs/5260776059/jobs/9508139568?pr=166
> Update settings.env to include bookworm

- repository-containers/images/github.com/microsoft/vscode/.devcontainer/base.Dockerfile
Needed for https://github.com/microsoft/vscode/pull/189882
> chore: update node version to v18

- build/config.json
- build/src/utils/config.js
microsoft/vscode-remote-release#8994
> Stop building VS Code image

- README.md
Update slightly to confirm this repo is archived and help folks find our new dev container home!
> Update README.md to confirm archival
